// Code generated by mockzilla-codegen. DO NOT EDIT.

package petstore

import (
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type PetModel struct {
	PetID *int64  `json:"id,omitempty"`
	Name  string  `json:"name"`
	Tag   *string `json:"tag,omitempty"`
	// Alternative names for the pet
	Nicknames []PetModelNicknamesItem `json:"nicknames,omitzero"`
}

// Validate checks the value against the constraints of the spec.
func (p PetModel) Validate() error {
	var errs validation.Errors
	for idx, item := range p.Nicknames {
		errs.Append(validation.Index("nicknames", idx), item.Validate())
	}
	return errs.Err()
}

type PetModelNicknamesItem string

const (
	PetModelNicknamesItemFluffy PetModelNicknamesItem = "Fluffy"
	PetModelNicknamesItemSpot   PetModelNicknamesItem = "Spot"
	PetModelNicknamesItemRover  PetModelNicknamesItem = "Rover"
)

// PetModelNicknamesItemValues returns the values of PetModelNicknamesItem.
func PetModelNicknamesItemValues() []PetModelNicknamesItem {
	return []PetModelNicknamesItem{
		PetModelNicknamesItemFluffy,
		PetModelNicknamesItemSpot,
		PetModelNicknamesItemRover,
	}
}

// Validate checks the value against the constraints of the spec.
func (p PetModelNicknamesItem) Validate() error {
	return validation.Enum(p, PetModelNicknamesItemFluffy, PetModelNicknamesItemSpot, PetModelNicknamesItemRover)
}

type GetPetPathParams struct {
	PetID string `json:"petId"`
}

type ListPetsResponse200 []PetModel

// Validate checks the value against the constraints of the spec.
func (l ListPetsResponse200) Validate() error {
	var errs validation.Errors
	for idx, item := range l {
		errs.Append(validation.Index("", idx), item.Validate())
	}
	return errs.Err()
}
