// Code generated by mockzilla-codegen. DO NOT EDIT.

package petstore

import (
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"sync"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla/v2/pkg/api"
	"github.com/mockzilla/mockzilla/v2/pkg/config"
	"github.com/mockzilla/mockzilla/v2/pkg/db"
	"github.com/mockzilla/mockzilla/v2/pkg/factory"
	"github.com/mockzilla/mockzilla/v2/pkg/generator"
	"github.com/mockzilla/mockzilla/v2/pkg/loader"
	"github.com/mockzilla/mockzilla/v2/pkg/schema"
	"github.com/mockzilla/mockzilla/v2/pkg/typedef"
)

//go:embed setup/config.yml
var configSrc []byte

//go:embed setup/openapi.*
var openapiSpecFS embed.FS

//go:embed setup/context.yml
var contextSrc []byte

// ServiceErrorHandler answers the requests that fail before the service is reached.
var ServiceErrorHandler ErrorHandler = DefaultErrorHandler{}

// cfg is set before any init function runs, so the package's other files can read it in theirs.
var cfg, cfgErr = config.NewServiceConfigFromBytes(configSrc)

func init() {
	if cfgErr != nil {
		slog.Error("Failed to parse service config", "error", cfgErr)
		return
	}
	loader.Register(cfg.Name, RegisterAPIRouter)
}

// RegisterAPIRouter registers the service with the central router.
func RegisterAPIRouter(router *api.Router) {
	serviceName := cfg.Name

	openapiSpec, err := api.ReadEmbeddedSpec(openapiSpecFS)
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to read OpenAPI spec for %s", serviceName), "error", err, "service", serviceName)
		return
	}

	registry, err := typedef.NewRegistry(openapiSpec, typedef.RegistryOptions{
		SpecOptions:     cfg.SpecOptions,
		ReleaseDocument: true,
	})
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to create registry for %s", serviceName), "error", err, "service", serviceName)
		return
	}

	orderedCtx := router.ServiceContext(serviceName, contextSrc)
	gen, err := generator.NewGenerator(orderedCtx, router.GetContexts())
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to create generator for %s", serviceName), "error", err, "service", serviceName)
		return
	}

	router.RegisterHTTPHandler(cfg, func(serviceDB db.DB) api.Handler {
		userSvc := newService(&api.ServiceParams{
			AppConfig:     router.Config(),
			ServiceConfig: cfg,
			DB:            serviceDB,
		})
		genSvc := &generatorService{service: userSvc, generator: gen, registry: registry}
		return newServiceHandler(genSvc, gen, registry)
	}, api.WithMiddleware(getMiddleware()))

	slog.Info(fmt.Sprintf("Registered %s service", serviceName), "service", serviceName)
}

type serviceHandler struct {
	router   chi.Router
	gen      generator.Generate
	registry typedef.OperationRegistry
}

func newServiceHandler(svc ServiceInterface, gen generator.Generate, registry typedef.OperationRegistry) api.Handler {
	return &serviceHandler{
		router: NewRouter(svc,
			WithMiddleware(api.ContextReplacementsMiddleware),
			WithErrorHandler(returnedErrors{next: ServiceErrorHandler}),
		),
		gen:      gen,
		registry: registry,
	}
}

func (h *serviceHandler) Routes() api.RouteDescriptions {
	routes := h.router.Routes()
	descriptions := make(api.RouteDescriptions, 0, len(routes))
	for _, route := range routes {
		for method := range route.Handlers {
			descriptions = append(descriptions, &api.RouteDescription{Method: method, Path: route.Pattern})
		}
	}
	return descriptions
}

func (h *serviceHandler) RegisterRoutes(router chi.Router) {
	router.Mount("/", h.router)
}

func (h *serviceHandler) Generate(w http.ResponseWriter, r *http.Request) {
	var req api.GenerateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		message := err.Error()
		if errors.Is(err, io.EOF) {
			message = "request body is empty or incomplete"
		}
		slog.Error("Failed to decode request", "error", err)
		http.Error(w, message, http.StatusBadRequest)
		return
	}

	op := h.registry.FindOperation(req.Path, req.Method)
	res := h.gen.Request(&req, op, req.Context)
	api.NewJSONResponse(w).Send(res)
}

// returnedError is an error the service returned, with the status of the response it returned too.
// It has no Unwrap, so the adapter cannot answer an error type of the spec before returnedErrors.
type returnedError struct {
	status int
	err    error
}

func (e *returnedError) Error() string {
	return e.err.Error()
}

// returnedErrors hands next an error the service returned as it was returned, with the status of
// its response, so a service answers an error with the status it sets.
type returnedErrors struct {
	next ErrorHandler
}

func (h returnedErrors) HandleError(w http.ResponseWriter, r *http.Request, status int, err error) {
	var returned *returnedError
	if errors.As(err, &returned) {
		if returned.status != 0 {
			status = returned.status
		}
		err = returned.err
	}
	h.next.HandleError(w, r, status, err)
}

// generatorService calls the service first and makes a mock response when it returns nil, nil.
type generatorService struct {
	service   *service
	generator generator.Generate
	registry  typedef.OperationRegistry
}

var _ ServiceInterface = (*generatorService)(nil)

func (s *generatorService) UpdatePet(ctx context.Context, opts *UpdatePetServiceRequestOptions) (*UpdatePetResponseData, error) {
	opts.GenerateResponse = func() (*UpdatePetResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pet", "PUT")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body Pet
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewUpdatePetResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.UpdatePet(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) AddPet(ctx context.Context, opts *AddPetServiceRequestOptions) (*AddPetResponseData, error) {
	opts.GenerateResponse = func() (*AddPetResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pet", "POST")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body Pet
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewAddPetResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.AddPet(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) FindPetsByStatus(ctx context.Context, opts *FindPetsByStatusServiceRequestOptions) (*FindPetsByStatusResponseData, error) {
	opts.GenerateResponse = func() (*FindPetsByStatusResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pet/findByStatus", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body FindPetsByStatusJSONResponse200
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewFindPetsByStatusResponseData200(body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.FindPetsByStatus(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) FindPetsByTags(ctx context.Context, opts *FindPetsByTagsServiceRequestOptions) (*FindPetsByTagsResponseData, error) {
	opts.GenerateResponse = func() (*FindPetsByTagsResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pet/findByTags", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body FindPetsByTagsJSONResponse200
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewFindPetsByTagsResponseData200(body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.FindPetsByTags(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetPetByID(ctx context.Context, opts *GetPetByIDServiceRequestOptions) (*GetPetByIDResponseData, error) {
	opts.GenerateResponse = func() (*GetPetByIDResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pet/{petId}", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body Pet
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewGetPetByIDResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetPetByID(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) UpdatePetWithForm(ctx context.Context, opts *UpdatePetWithFormServiceRequestOptions) (*UpdatePetWithFormResponseData, error) {
	opts.GenerateResponse = func() (*UpdatePetWithFormResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pet/{petId}", "POST")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body Pet
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewUpdatePetWithFormResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.UpdatePetWithForm(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) DeletePet(ctx context.Context, opts *DeletePetServiceRequestOptions) (*DeletePetResponseData, error) {
	opts.GenerateResponse = func() (*DeletePetResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pet/{petId}", "DELETE")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		return NewDeletePetResponseData200().WithHeaders(res.Headers), nil
	}

	resp, err := s.service.DeletePet(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) UploadFile(ctx context.Context, opts *UploadFileServiceRequestOptions) (*UploadFileResponseData, error) {
	opts.GenerateResponse = func() (*UploadFileResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/pet/{petId}/uploadImage", "POST")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body APIResponse
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewUploadFileResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.UploadFile(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetInventory(ctx context.Context, opts *GetInventoryServiceRequestOptions) (*GetInventoryResponseData, error) {
	opts.GenerateResponse = func() (*GetInventoryResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/store/inventory", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body GetInventoryResponse200
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewGetInventoryResponseData200(body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetInventory(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) PlaceOrder(ctx context.Context, opts *PlaceOrderServiceRequestOptions) (*PlaceOrderResponseData, error) {
	opts.GenerateResponse = func() (*PlaceOrderResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/store/order", "POST")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body Order
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewPlaceOrderResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.PlaceOrder(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetOrderByID(ctx context.Context, opts *GetOrderByIDServiceRequestOptions) (*GetOrderByIDResponseData, error) {
	opts.GenerateResponse = func() (*GetOrderByIDResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/store/order/{orderId}", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body Order
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewGetOrderByIDResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetOrderByID(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) DeleteOrder(ctx context.Context, opts *DeleteOrderServiceRequestOptions) (*DeleteOrderResponseData, error) {
	opts.GenerateResponse = func() (*DeleteOrderResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/store/order/{orderId}", "DELETE")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		return NewDeleteOrderResponseData200().WithHeaders(res.Headers), nil
	}

	resp, err := s.service.DeleteOrder(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) CreateUser(ctx context.Context, opts *CreateUserServiceRequestOptions) (*CreateUserResponseData, error) {
	opts.GenerateResponse = func() (*CreateUserResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/user", "POST")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body User
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewCreateUserResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.CreateUser(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) CreateUsersWithListInput(ctx context.Context, opts *CreateUsersWithListInputServiceRequestOptions) (*CreateUsersWithListInputResponseData, error) {
	opts.GenerateResponse = func() (*CreateUsersWithListInputResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/user/createWithList", "POST")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body User
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewCreateUsersWithListInputResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.CreateUsersWithListInput(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) LoginUser(ctx context.Context, opts *LoginUserServiceRequestOptions) (*LoginUserResponseData, error) {
	opts.GenerateResponse = func() (*LoginUserResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/user/login", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body LoginUserJSONResponse200
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewLoginUserResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.LoginUser(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) LogoutUser(ctx context.Context, opts *LogoutUserServiceRequestOptions) (*LogoutUserResponseData, error) {
	opts.GenerateResponse = func() (*LogoutUserResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/user/logout", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		return NewLogoutUserResponseData200().WithHeaders(res.Headers), nil
	}

	resp, err := s.service.LogoutUser(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetUserByName(ctx context.Context, opts *GetUserByNameServiceRequestOptions) (*GetUserByNameResponseData, error) {
	opts.GenerateResponse = func() (*GetUserByNameResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/user/{username}", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body User
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewGetUserByNameResponseData200(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetUserByName(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) UpdateUser(ctx context.Context, opts *UpdateUserServiceRequestOptions) (*UpdateUserResponseData, error) {
	opts.GenerateResponse = func() (*UpdateUserResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/user/{username}", "PUT")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		return NewUpdateUserResponseData200().WithHeaders(res.Headers), nil
	}

	resp, err := s.service.UpdateUser(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) DeleteUser(ctx context.Context, opts *DeleteUserServiceRequestOptions) (*DeleteUserResponseData, error) {
	opts.GenerateResponse = func() (*DeleteUserResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/user/{username}", "DELETE")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		return NewDeleteUserResponseData200().WithHeaders(res.Headers), nil
	}

	resp, err := s.service.DeleteUser(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

var (
	defaultFactory     *factory.Factory
	defaultFactoryOnce sync.Once
	defaultFactoryErr  error
)

// NewFactory returns a Factory with the spec, spec options and context of this service.
func NewFactory(opts ...factory.FactoryOption) (*factory.Factory, error) {
	openapiSpec, err := api.ReadEmbeddedSpec(openapiSpecFS)
	if err != nil {
		return nil, err
	}

	allOpts := []factory.FactoryOption{factory.WithServiceContext(contextSrc)}
	if cfg != nil && cfg.SpecOptions != nil {
		allOpts = append(allOpts, factory.WithSpecOptions(cfg.SpecOptions))
	}
	allOpts = append(allOpts, opts...)
	return factory.NewFactory(openapiSpec, allOpts...)
}

// GetFactory returns the Factory of this service, made on the first call.
func GetFactory() (*factory.Factory, error) {
	defaultFactoryOnce.Do(func() {
		defaultFactory, defaultFactoryErr = NewFactory()
	})
	return defaultFactory, defaultFactoryErr
}

// GenerateUpdatePetResponse makes a mock response for PUT /pet.
func GenerateUpdatePetResponse(ctx map[string]any) (*UpdatePetResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pet", "PUT", ctx)
	if err != nil {
		return nil, err
	}
	var body Pet
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewUpdatePetResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateUpdatePetRequest makes a mock request for PUT /pet.
func GenerateUpdatePetRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pet", "PUT", ctx)
}

// GenerateUpdatePetRequestBody makes a typed mock request body for PUT /pet.
func GenerateUpdatePetRequestBody(ctx map[string]any) (*Pet, error) {
	req, err := GenerateUpdatePetRequest(ctx)
	if err != nil {
		return nil, err
	}
	body := new(Pet)
	if err := json.Unmarshal(req.Body, body); err != nil {
		return nil, err
	}
	return body, nil
}

// GenerateAddPetResponse makes a mock response for POST /pet.
func GenerateAddPetResponse(ctx map[string]any) (*AddPetResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pet", "POST", ctx)
	if err != nil {
		return nil, err
	}
	var body Pet
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewAddPetResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateAddPetRequest makes a mock request for POST /pet.
func GenerateAddPetRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pet", "POST", ctx)
}

// GenerateAddPetRequestBody makes a typed mock request body for POST /pet.
func GenerateAddPetRequestBody(ctx map[string]any) (*Pet, error) {
	req, err := GenerateAddPetRequest(ctx)
	if err != nil {
		return nil, err
	}
	body := new(Pet)
	if err := json.Unmarshal(req.Body, body); err != nil {
		return nil, err
	}
	return body, nil
}

// GenerateFindPetsByStatusResponse makes a mock response for GET /pet/findByStatus.
func GenerateFindPetsByStatusResponse(ctx map[string]any) (*FindPetsByStatusResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pet/findByStatus", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body FindPetsByStatusJSONResponse200
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewFindPetsByStatusResponseData200(body).WithHeaders(res.Headers), nil
}

// GenerateFindPetsByStatusRequest makes a mock request for GET /pet/findByStatus.
func GenerateFindPetsByStatusRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pet/findByStatus", "GET", ctx)
}

// GenerateFindPetsByTagsResponse makes a mock response for GET /pet/findByTags.
func GenerateFindPetsByTagsResponse(ctx map[string]any) (*FindPetsByTagsResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pet/findByTags", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body FindPetsByTagsJSONResponse200
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewFindPetsByTagsResponseData200(body).WithHeaders(res.Headers), nil
}

// GenerateFindPetsByTagsRequest makes a mock request for GET /pet/findByTags.
func GenerateFindPetsByTagsRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pet/findByTags", "GET", ctx)
}

// GenerateGetPetByIDResponse makes a mock response for GET /pet/{petId}.
func GenerateGetPetByIDResponse(ctx map[string]any) (*GetPetByIDResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pet/{petId}", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body Pet
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewGetPetByIDResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateGetPetByIDRequest makes a mock request for GET /pet/{petId}.
func GenerateGetPetByIDRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pet/{petId}", "GET", ctx)
}

// GenerateUpdatePetWithFormResponse makes a mock response for POST /pet/{petId}.
func GenerateUpdatePetWithFormResponse(ctx map[string]any) (*UpdatePetWithFormResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pet/{petId}", "POST", ctx)
	if err != nil {
		return nil, err
	}
	var body Pet
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewUpdatePetWithFormResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateUpdatePetWithFormRequest makes a mock request for POST /pet/{petId}.
func GenerateUpdatePetWithFormRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pet/{petId}", "POST", ctx)
}

// GenerateDeletePetResponse makes a mock response for DELETE /pet/{petId}.
func GenerateDeletePetResponse(ctx map[string]any) (*DeletePetResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pet/{petId}", "DELETE", ctx)
	if err != nil {
		return nil, err
	}
	return NewDeletePetResponseData200().WithHeaders(res.Headers), nil
}

// GenerateDeletePetRequest makes a mock request for DELETE /pet/{petId}.
func GenerateDeletePetRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pet/{petId}", "DELETE", ctx)
}

// GenerateUploadFileResponse makes a mock response for POST /pet/{petId}/uploadImage.
func GenerateUploadFileResponse(ctx map[string]any) (*UploadFileResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/pet/{petId}/uploadImage", "POST", ctx)
	if err != nil {
		return nil, err
	}
	var body APIResponse
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewUploadFileResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateUploadFileRequest makes a mock request for POST /pet/{petId}/uploadImage.
func GenerateUploadFileRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/pet/{petId}/uploadImage", "POST", ctx)
}

// GenerateGetInventoryResponse makes a mock response for GET /store/inventory.
func GenerateGetInventoryResponse(ctx map[string]any) (*GetInventoryResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/store/inventory", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body GetInventoryResponse200
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewGetInventoryResponseData200(body).WithHeaders(res.Headers), nil
}

// GenerateGetInventoryRequest makes a mock request for GET /store/inventory.
func GenerateGetInventoryRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/store/inventory", "GET", ctx)
}

// GeneratePlaceOrderResponse makes a mock response for POST /store/order.
func GeneratePlaceOrderResponse(ctx map[string]any) (*PlaceOrderResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/store/order", "POST", ctx)
	if err != nil {
		return nil, err
	}
	var body Order
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewPlaceOrderResponseData200(&body).WithHeaders(res.Headers), nil
}

// GeneratePlaceOrderRequest makes a mock request for POST /store/order.
func GeneratePlaceOrderRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/store/order", "POST", ctx)
}

// GeneratePlaceOrderRequestBody makes a typed mock request body for POST /store/order.
func GeneratePlaceOrderRequestBody(ctx map[string]any) (*Order, error) {
	req, err := GeneratePlaceOrderRequest(ctx)
	if err != nil {
		return nil, err
	}
	body := new(Order)
	if err := json.Unmarshal(req.Body, body); err != nil {
		return nil, err
	}
	return body, nil
}

// GenerateGetOrderByIDResponse makes a mock response for GET /store/order/{orderId}.
func GenerateGetOrderByIDResponse(ctx map[string]any) (*GetOrderByIDResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/store/order/{orderId}", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body Order
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewGetOrderByIDResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateGetOrderByIDRequest makes a mock request for GET /store/order/{orderId}.
func GenerateGetOrderByIDRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/store/order/{orderId}", "GET", ctx)
}

// GenerateDeleteOrderResponse makes a mock response for DELETE /store/order/{orderId}.
func GenerateDeleteOrderResponse(ctx map[string]any) (*DeleteOrderResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/store/order/{orderId}", "DELETE", ctx)
	if err != nil {
		return nil, err
	}
	return NewDeleteOrderResponseData200().WithHeaders(res.Headers), nil
}

// GenerateDeleteOrderRequest makes a mock request for DELETE /store/order/{orderId}.
func GenerateDeleteOrderRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/store/order/{orderId}", "DELETE", ctx)
}

// GenerateCreateUserResponse makes a mock response for POST /user.
func GenerateCreateUserResponse(ctx map[string]any) (*CreateUserResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/user", "POST", ctx)
	if err != nil {
		return nil, err
	}
	var body User
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewCreateUserResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateCreateUserRequest makes a mock request for POST /user.
func GenerateCreateUserRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/user", "POST", ctx)
}

// GenerateCreateUserRequestBody makes a typed mock request body for POST /user.
func GenerateCreateUserRequestBody(ctx map[string]any) (*User, error) {
	req, err := GenerateCreateUserRequest(ctx)
	if err != nil {
		return nil, err
	}
	body := new(User)
	if err := json.Unmarshal(req.Body, body); err != nil {
		return nil, err
	}
	return body, nil
}

// GenerateCreateUsersWithListInputResponse makes a mock response for POST /user/createWithList.
func GenerateCreateUsersWithListInputResponse(ctx map[string]any) (*CreateUsersWithListInputResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/user/createWithList", "POST", ctx)
	if err != nil {
		return nil, err
	}
	var body User
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewCreateUsersWithListInputResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateCreateUsersWithListInputRequest makes a mock request for POST /user/createWithList.
func GenerateCreateUsersWithListInputRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/user/createWithList", "POST", ctx)
}

// GenerateLoginUserResponse makes a mock response for GET /user/login.
func GenerateLoginUserResponse(ctx map[string]any) (*LoginUserResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/user/login", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body LoginUserJSONResponse200
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewLoginUserResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateLoginUserRequest makes a mock request for GET /user/login.
func GenerateLoginUserRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/user/login", "GET", ctx)
}

// GenerateLogoutUserResponse makes a mock response for GET /user/logout.
func GenerateLogoutUserResponse(ctx map[string]any) (*LogoutUserResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/user/logout", "GET", ctx)
	if err != nil {
		return nil, err
	}
	return NewLogoutUserResponseData200().WithHeaders(res.Headers), nil
}

// GenerateLogoutUserRequest makes a mock request for GET /user/logout.
func GenerateLogoutUserRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/user/logout", "GET", ctx)
}

// GenerateGetUserByNameResponse makes a mock response for GET /user/{username}.
func GenerateGetUserByNameResponse(ctx map[string]any) (*GetUserByNameResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/user/{username}", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body User
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewGetUserByNameResponseData200(&body).WithHeaders(res.Headers), nil
}

// GenerateGetUserByNameRequest makes a mock request for GET /user/{username}.
func GenerateGetUserByNameRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/user/{username}", "GET", ctx)
}

// GenerateUpdateUserResponse makes a mock response for PUT /user/{username}.
func GenerateUpdateUserResponse(ctx map[string]any) (*UpdateUserResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/user/{username}", "PUT", ctx)
	if err != nil {
		return nil, err
	}
	return NewUpdateUserResponseData200().WithHeaders(res.Headers), nil
}

// GenerateUpdateUserRequest makes a mock request for PUT /user/{username}.
func GenerateUpdateUserRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/user/{username}", "PUT", ctx)
}

// GenerateUpdateUserRequestBody makes a typed mock request body for PUT /user/{username}.
func GenerateUpdateUserRequestBody(ctx map[string]any) (*User, error) {
	req, err := GenerateUpdateUserRequest(ctx)
	if err != nil {
		return nil, err
	}
	body := new(User)
	if err := json.Unmarshal(req.Body, body); err != nil {
		return nil, err
	}
	return body, nil
}

// GenerateDeleteUserResponse makes a mock response for DELETE /user/{username}.
func GenerateDeleteUserResponse(ctx map[string]any) (*DeleteUserResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/user/{username}", "DELETE", ctx)
	if err != nil {
		return nil, err
	}
	return NewDeleteUserResponseData200().WithHeaders(res.Headers), nil
}

// GenerateDeleteUserRequest makes a mock request for DELETE /user/{username}.
func GenerateDeleteUserRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/user/{username}", "DELETE", ctx)
}
