import { resolveConfigUrl } from './url.js';

export const url = window.location.origin;
export const baseUrl = resolveConfigUrl(url, appConfig.baseUrl);
export const serviceUrl = resolveConfigUrl(url, appConfig.serviceUrl);
export const historyEnabled = !!appConfig.historyUrl;
export const historyUrl = resolveConfigUrl(url, appConfig.historyUrl);
export const replayEnabled = !!appConfig.replayUrl;
export const replayUrl = resolveConfigUrl(url, appConfig.replayUrl);
export const configEnabled = !appConfig.disableConfigUI;
export const version = appConfig.version;
export const editor = appConfig.editor;
export const homeContents = document.getElementById('home-contents');
export const serviceList = document.getElementById('service-list');
export const servicesLink = document.getElementById('services-link');
export const generatorCont = document.getElementById('generator-container');
export const contentTitleEl = document.getElementById('container-title');
export const iframeContents = document.getElementById('iframe-contents');
export const messageCont = document.getElementById('message');
export const fixedServiceContainer = document.getElementById('fixed-service-container');
export const resourceRefreshBtn = document.getElementById('refresh');
export const historyContainer = fixedServiceContainer;
export const serviceTabs = document.getElementById('service-tabs');
export const tabResources = document.getElementById('tab-resources');
export const tabHistory = document.getElementById('tab-history');
export const tabReplay = document.getElementById('tab-replay');
export const tabConfiguration = document.getElementById('tab-configuration');
export const configurationContainer = fixedServiceContainer;
