// Code generated by mockzilla-codegen. DO NOT EDIT.

package petstore

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"time"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpserver"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type Order struct {
	ID       *int64       `json:"id,omitempty"`
	PetID    *int64       `json:"petId,omitempty"`
	Quantity *int32       `json:"quantity,omitempty"`
	ShipDate *time.Time   `json:"shipDate,omitempty"`
	Status   *OrderStatus `json:"status,omitempty"`
	Complete *bool        `json:"complete,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (o Order) Validate() error {
	var errs validation.Errors
	if o.Status != nil {
		errs.Append("status", o.Status.Validate())
	}
	return errs.Err()
}

type Category struct {
	ID   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type User struct {
	ID         *int64  `json:"id,omitempty"`
	Username   *string `json:"username,omitempty"`
	FirstName  *string `json:"firstName,omitempty"`
	LastName   *string `json:"lastName,omitempty"`
	Email      *string `json:"email,omitempty"`
	Password   *string `json:"password,omitempty"`
	Phone      *string `json:"phone,omitempty"`
	UserStatus *int32  `json:"userStatus,omitempty"`
}

type Tag struct {
	ID   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type Pet struct {
	ID        *int64     `json:"id,omitempty"`
	Name      string     `json:"name"`
	Category  *Category  `json:"category,omitempty"`
	PhotoURLs []string   `json:"photoUrls"`
	Tags      []Tag      `json:"tags,omitzero"`
	Status    *PetStatus `json:"status,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (p Pet) Validate() error {
	var errs validation.Errors
	if p.PhotoURLs == nil {
		errs.Required("photoUrls")
	}
	if p.Status != nil {
		errs.Append("status", p.Status.Validate())
	}
	return errs.Err()
}

type APIResponse struct {
	Code    *int32  `json:"code,omitempty"`
	Type    *string `json:"type,omitempty"`
	Message *string `json:"message,omitempty"`
}

type OrderStatus string

const (
	OrderStatusPlaced    OrderStatus = "placed"
	OrderStatusApproved  OrderStatus = "approved"
	OrderStatusDelivered OrderStatus = "delivered"
)

// OrderStatusValues returns the values of OrderStatus.
func OrderStatusValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPlaced,
		OrderStatusApproved,
		OrderStatusDelivered,
	}
}

// Validate checks the value against the constraints of the spec.
func (o OrderStatus) Validate() error {
	return validation.Enum(o, OrderStatusPlaced, OrderStatusApproved, OrderStatusDelivered)
}

type PetStatus string

const (
	PetStatusAvailable PetStatus = "available"
	PetStatusPending   PetStatus = "pending"
	PetStatusSold      PetStatus = "sold"
)

// PetStatusValues returns the values of PetStatus.
func PetStatusValues() []PetStatus {
	return []PetStatus{
		PetStatusAvailable,
		PetStatusPending,
		PetStatusSold,
	}
}

// Validate checks the value against the constraints of the spec.
func (p PetStatus) Validate() error {
	return validation.Enum(p, PetStatusAvailable, PetStatusPending, PetStatusSold)
}

type FindPetsByStatusQueryStatus string

const (
	FindPetsByStatusQueryStatusAvailable FindPetsByStatusQueryStatus = "available"
	FindPetsByStatusQueryStatusPending   FindPetsByStatusQueryStatus = "pending"
	FindPetsByStatusQueryStatusSold      FindPetsByStatusQueryStatus = "sold"
)

// FindPetsByStatusQueryStatusValues returns the values of FindPetsByStatusQueryStatus.
func FindPetsByStatusQueryStatusValues() []FindPetsByStatusQueryStatus {
	return []FindPetsByStatusQueryStatus{
		FindPetsByStatusQueryStatusAvailable,
		FindPetsByStatusQueryStatusPending,
		FindPetsByStatusQueryStatusSold,
	}
}

// Validate checks the value against the constraints of the spec.
func (f FindPetsByStatusQueryStatus) Validate() error {
	return validation.Enum(f, FindPetsByStatusQueryStatusAvailable, FindPetsByStatusQueryStatusPending, FindPetsByStatusQueryStatusSold)
}

type FindPetsByStatusQuery struct {
	Status FindPetsByStatusQueryStatus `json:"status"`
}

// Validate checks the value against the constraints of the spec.
func (f FindPetsByStatusQuery) Validate() error {
	var errs validation.Errors
	errs.Append("status", f.Status.Validate())
	return errs.Err()
}

type FindPetsByTagsQuery struct {
	Tags []string `json:"tags"`
}

// Validate checks the value against the constraints of the spec.
func (f FindPetsByTagsQuery) Validate() error {
	var errs validation.Errors
	if f.Tags == nil {
		errs.Required("tags")
	}
	return errs.Err()
}

type GetPetByIDPathParams struct {
	PetID int64 `json:"petId"`
}

type UpdatePetWithFormPathParams struct {
	PetID int64 `json:"petId"`
}

type UpdatePetWithFormQuery struct {
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

type DeletePetPathParams struct {
	PetID int64 `json:"petId"`
}

type DeletePetHeaders struct {
	APIKey *string `json:"api_key,omitempty"`
}

type UploadFilePathParams struct {
	PetID int64 `json:"petId"`
}

type UploadFileQuery struct {
	AdditionalMetadata *string `json:"additionalMetadata,omitempty"`
}

type GetOrderByIDPathParams struct {
	OrderID int64 `json:"orderId"`
}

type DeleteOrderPathParams struct {
	OrderID int64 `json:"orderId"`
}

type LoginUserQuery struct {
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}

type GetUserByNamePathParams struct {
	Username string `json:"username"`
}

type UpdateUserPathParams struct {
	Username string `json:"username"`
}

type DeleteUserPathParams struct {
	Username string `json:"username"`
}

type UploadFileRequestBody = runtime.File

type CreateUsersWithListInputRequestBody []User

type FindPetsByStatusJSONResponse200 []Pet

// Validate checks the value against the constraints of the spec.
func (f FindPetsByStatusJSONResponse200) Validate() error {
	var errs validation.Errors
	for idx, item := range f {
		errs.Append(validation.Index("", idx), item.Validate())
	}
	return errs.Err()
}

type FindPetsByStatusXMLResponse200 []Pet

// Validate checks the value against the constraints of the spec.
func (f FindPetsByStatusXMLResponse200) Validate() error {
	var errs validation.Errors
	for idx, item := range f {
		errs.Append(validation.Index("", idx), item.Validate())
	}
	return errs.Err()
}

type FindPetsByTagsJSONResponse200 []Pet

// Validate checks the value against the constraints of the spec.
func (f FindPetsByTagsJSONResponse200) Validate() error {
	var errs validation.Errors
	for idx, item := range f {
		errs.Append(validation.Index("", idx), item.Validate())
	}
	return errs.Err()
}

type FindPetsByTagsXMLResponse200 []Pet

// Validate checks the value against the constraints of the spec.
func (f FindPetsByTagsXMLResponse200) Validate() error {
	var errs validation.Errors
	for idx, item := range f {
		errs.Append(validation.Index("", idx), item.Validate())
	}
	return errs.Err()
}

type GetInventoryResponse200 map[string]int32

type LoginUserXMLResponse200 = string

type LoginUserJSONResponse200 = string

type LoginUserResponse200Headers struct {
	XRateLimit    *int32     `json:"X-Rate-Limit,omitempty"`
	XExpiresAfter *time.Time `json:"X-Expires-After,omitempty"`
}

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// UpdatePet handles PUT /pet.
	UpdatePet(ctx context.Context, opts *UpdatePetServiceRequestOptions) (*UpdatePetResponseData, error)
	// AddPet handles POST /pet.
	AddPet(ctx context.Context, opts *AddPetServiceRequestOptions) (*AddPetResponseData, error)
	// FindPetsByStatus handles GET /pet/findByStatus.
	FindPetsByStatus(ctx context.Context, opts *FindPetsByStatusServiceRequestOptions) (*FindPetsByStatusResponseData, error)
	// FindPetsByTags handles GET /pet/findByTags.
	FindPetsByTags(ctx context.Context, opts *FindPetsByTagsServiceRequestOptions) (*FindPetsByTagsResponseData, error)
	// GetPetByID handles GET /pet/{petId}.
	GetPetByID(ctx context.Context, opts *GetPetByIDServiceRequestOptions) (*GetPetByIDResponseData, error)
	// UpdatePetWithForm handles POST /pet/{petId}.
	UpdatePetWithForm(ctx context.Context, opts *UpdatePetWithFormServiceRequestOptions) (*UpdatePetWithFormResponseData, error)
	// DeletePet handles DELETE /pet/{petId}.
	DeletePet(ctx context.Context, opts *DeletePetServiceRequestOptions) (*DeletePetResponseData, error)
	// UploadFile handles POST /pet/{petId}/uploadImage.
	UploadFile(ctx context.Context, opts *UploadFileServiceRequestOptions) (*UploadFileResponseData, error)
	// GetInventory handles GET /store/inventory.
	GetInventory(ctx context.Context, opts *GetInventoryServiceRequestOptions) (*GetInventoryResponseData, error)
	// PlaceOrder handles POST /store/order.
	PlaceOrder(ctx context.Context, opts *PlaceOrderServiceRequestOptions) (*PlaceOrderResponseData, error)
	// GetOrderByID handles GET /store/order/{orderId}.
	GetOrderByID(ctx context.Context, opts *GetOrderByIDServiceRequestOptions) (*GetOrderByIDResponseData, error)
	// DeleteOrder handles DELETE /store/order/{orderId}.
	DeleteOrder(ctx context.Context, opts *DeleteOrderServiceRequestOptions) (*DeleteOrderResponseData, error)
	// CreateUser handles POST /user.
	CreateUser(ctx context.Context, opts *CreateUserServiceRequestOptions) (*CreateUserResponseData, error)
	// CreateUsersWithListInput handles POST /user/createWithList.
	CreateUsersWithListInput(ctx context.Context, opts *CreateUsersWithListInputServiceRequestOptions) (*CreateUsersWithListInputResponseData, error)
	// LoginUser handles GET /user/login.
	LoginUser(ctx context.Context, opts *LoginUserServiceRequestOptions) (*LoginUserResponseData, error)
	// LogoutUser handles GET /user/logout.
	LogoutUser(ctx context.Context, opts *LogoutUserServiceRequestOptions) (*LogoutUserResponseData, error)
	// GetUserByName handles GET /user/{username}.
	GetUserByName(ctx context.Context, opts *GetUserByNameServiceRequestOptions) (*GetUserByNameResponseData, error)
	// UpdateUser handles PUT /user/{username}.
	UpdateUser(ctx context.Context, opts *UpdateUserServiceRequestOptions) (*UpdateUserResponseData, error)
	// DeleteUser handles DELETE /user/{username}.
	DeleteUser(ctx context.Context, opts *DeleteUserServiceRequestOptions) (*DeleteUserResponseData, error)
}

// UpdatePetServiceRequestOptions is what UpdatePet receives.
type UpdatePetServiceRequestOptions struct {
	// Body sent as application/json.
	BodyJSON *Pet
	// Body sent as application/xml.
	BodyXML *Pet
	// Body sent as application/x-www-form-urlencoded.
	BodyForm *Pet
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*UpdatePetResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *UpdatePetServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.BodyJSON != nil {
		errs.Append("body", o.BodyJSON.Validate())
	}
	if o.BodyXML != nil {
		errs.Append("body", o.BodyXML.Validate())
	}
	if o.BodyForm != nil {
		errs.Append("body", o.BodyForm.Validate())
	}
	return errs.Err()
}

// UpdatePetResponseData is what UpdatePet returns.
type UpdatePetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewUpdatePetResponseData200 returns the 200 response with its application/json body.
func NewUpdatePetResponseData200(body *Pet) *UpdatePetResponseData {
	return &UpdatePetResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewUpdatePetResponseData400 returns the 400 response.
func NewUpdatePetResponseData400() *UpdatePetResponseData {
	return &UpdatePetResponseData{Status: 400, contentType: ""}
}

// NewUpdatePetResponseData404 returns the 404 response.
func NewUpdatePetResponseData404() *UpdatePetResponseData {
	return &UpdatePetResponseData{Status: 404, contentType: ""}
}

// NewUpdatePetResponseData422 returns the 422 response.
func NewUpdatePetResponseData422() *UpdatePetResponseData {
	return &UpdatePetResponseData{Status: 422, contentType: ""}
}

// NewUpdatePetResponseDataDefault returns the default response.
func NewUpdatePetResponseDataDefault(status int) *UpdatePetResponseData {
	return &UpdatePetResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *UpdatePetResponseData) WithStatus(code int) *UpdatePetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *UpdatePetResponseData) WithHeaders(h http.Header) *UpdatePetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *UpdatePetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *UpdatePetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *UpdatePetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *UpdatePetResponseData) ContentType() string {
	return r.contentType
}

// AddPetServiceRequestOptions is what AddPet receives.
type AddPetServiceRequestOptions struct {
	// Body sent as application/json.
	BodyJSON *Pet
	// Body sent as application/xml.
	BodyXML *Pet
	// Body sent as application/x-www-form-urlencoded.
	BodyForm *Pet
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*AddPetResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *AddPetServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.BodyJSON != nil {
		errs.Append("body", o.BodyJSON.Validate())
	}
	if o.BodyXML != nil {
		errs.Append("body", o.BodyXML.Validate())
	}
	if o.BodyForm != nil {
		errs.Append("body", o.BodyForm.Validate())
	}
	return errs.Err()
}

// AddPetResponseData is what AddPet returns.
type AddPetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewAddPetResponseData200 returns the 200 response with its application/json body.
func NewAddPetResponseData200(body *Pet) *AddPetResponseData {
	return &AddPetResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewAddPetResponseData400 returns the 400 response.
func NewAddPetResponseData400() *AddPetResponseData {
	return &AddPetResponseData{Status: 400, contentType: ""}
}

// NewAddPetResponseData422 returns the 422 response.
func NewAddPetResponseData422() *AddPetResponseData {
	return &AddPetResponseData{Status: 422, contentType: ""}
}

// NewAddPetResponseDataDefault returns the default response.
func NewAddPetResponseDataDefault(status int) *AddPetResponseData {
	return &AddPetResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *AddPetResponseData) WithStatus(code int) *AddPetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *AddPetResponseData) WithHeaders(h http.Header) *AddPetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *AddPetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *AddPetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *AddPetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *AddPetResponseData) ContentType() string {
	return r.contentType
}

// FindPetsByStatusServiceRequestOptions is what FindPetsByStatus receives.
type FindPetsByStatusServiceRequestOptions struct {
	Query *FindPetsByStatusQuery
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*FindPetsByStatusResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *FindPetsByStatusServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Query != nil {
		errs.Append("query", o.Query.Validate())
	}
	return errs.Err()
}

// FindPetsByStatusResponseData is what FindPetsByStatus returns.
type FindPetsByStatusResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewFindPetsByStatusResponseData200 returns the 200 response with its application/json body.
func NewFindPetsByStatusResponseData200(body FindPetsByStatusJSONResponse200) *FindPetsByStatusResponseData {
	return &FindPetsByStatusResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewFindPetsByStatusResponseData400 returns the 400 response.
func NewFindPetsByStatusResponseData400() *FindPetsByStatusResponseData {
	return &FindPetsByStatusResponseData{Status: 400, contentType: ""}
}

// NewFindPetsByStatusResponseDataDefault returns the default response.
func NewFindPetsByStatusResponseDataDefault(status int) *FindPetsByStatusResponseData {
	return &FindPetsByStatusResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *FindPetsByStatusResponseData) WithStatus(code int) *FindPetsByStatusResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *FindPetsByStatusResponseData) WithHeaders(h http.Header) *FindPetsByStatusResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *FindPetsByStatusResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *FindPetsByStatusResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *FindPetsByStatusResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *FindPetsByStatusResponseData) ContentType() string {
	return r.contentType
}

// FindPetsByTagsServiceRequestOptions is what FindPetsByTags receives.
type FindPetsByTagsServiceRequestOptions struct {
	Query *FindPetsByTagsQuery
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*FindPetsByTagsResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *FindPetsByTagsServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Query != nil {
		errs.Append("query", o.Query.Validate())
	}
	return errs.Err()
}

// FindPetsByTagsResponseData is what FindPetsByTags returns.
type FindPetsByTagsResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewFindPetsByTagsResponseData200 returns the 200 response with its application/json body.
func NewFindPetsByTagsResponseData200(body FindPetsByTagsJSONResponse200) *FindPetsByTagsResponseData {
	return &FindPetsByTagsResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewFindPetsByTagsResponseData400 returns the 400 response.
func NewFindPetsByTagsResponseData400() *FindPetsByTagsResponseData {
	return &FindPetsByTagsResponseData{Status: 400, contentType: ""}
}

// NewFindPetsByTagsResponseDataDefault returns the default response.
func NewFindPetsByTagsResponseDataDefault(status int) *FindPetsByTagsResponseData {
	return &FindPetsByTagsResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *FindPetsByTagsResponseData) WithStatus(code int) *FindPetsByTagsResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *FindPetsByTagsResponseData) WithHeaders(h http.Header) *FindPetsByTagsResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *FindPetsByTagsResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *FindPetsByTagsResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *FindPetsByTagsResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *FindPetsByTagsResponseData) ContentType() string {
	return r.contentType
}

// GetPetByIDServiceRequestOptions is what GetPetByID receives.
type GetPetByIDServiceRequestOptions struct {
	PathParams *GetPetByIDPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetPetByIDResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetPetByIDServiceRequestOptions) Validate() error {
	return nil
}

// GetPetByIDResponseData is what GetPetByID returns.
type GetPetByIDResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetPetByIDResponseData200 returns the 200 response with its application/json body.
func NewGetPetByIDResponseData200(body *Pet) *GetPetByIDResponseData {
	return &GetPetByIDResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewGetPetByIDResponseData400 returns the 400 response.
func NewGetPetByIDResponseData400() *GetPetByIDResponseData {
	return &GetPetByIDResponseData{Status: 400, contentType: ""}
}

// NewGetPetByIDResponseData404 returns the 404 response.
func NewGetPetByIDResponseData404() *GetPetByIDResponseData {
	return &GetPetByIDResponseData{Status: 404, contentType: ""}
}

// NewGetPetByIDResponseDataDefault returns the default response.
func NewGetPetByIDResponseDataDefault(status int) *GetPetByIDResponseData {
	return &GetPetByIDResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *GetPetByIDResponseData) WithStatus(code int) *GetPetByIDResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetPetByIDResponseData) WithHeaders(h http.Header) *GetPetByIDResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetPetByIDResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetPetByIDResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetPetByIDResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetPetByIDResponseData) ContentType() string {
	return r.contentType
}

// UpdatePetWithFormServiceRequestOptions is what UpdatePetWithForm receives.
type UpdatePetWithFormServiceRequestOptions struct {
	PathParams *UpdatePetWithFormPathParams
	Query      *UpdatePetWithFormQuery
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*UpdatePetWithFormResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *UpdatePetWithFormServiceRequestOptions) Validate() error {
	return nil
}

// UpdatePetWithFormResponseData is what UpdatePetWithForm returns.
type UpdatePetWithFormResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewUpdatePetWithFormResponseData200 returns the 200 response with its application/json body.
func NewUpdatePetWithFormResponseData200(body *Pet) *UpdatePetWithFormResponseData {
	return &UpdatePetWithFormResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewUpdatePetWithFormResponseData400 returns the 400 response.
func NewUpdatePetWithFormResponseData400() *UpdatePetWithFormResponseData {
	return &UpdatePetWithFormResponseData{Status: 400, contentType: ""}
}

// NewUpdatePetWithFormResponseDataDefault returns the default response.
func NewUpdatePetWithFormResponseDataDefault(status int) *UpdatePetWithFormResponseData {
	return &UpdatePetWithFormResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *UpdatePetWithFormResponseData) WithStatus(code int) *UpdatePetWithFormResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *UpdatePetWithFormResponseData) WithHeaders(h http.Header) *UpdatePetWithFormResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *UpdatePetWithFormResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *UpdatePetWithFormResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *UpdatePetWithFormResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *UpdatePetWithFormResponseData) ContentType() string {
	return r.contentType
}

// DeletePetServiceRequestOptions is what DeletePet receives.
type DeletePetServiceRequestOptions struct {
	PathParams *DeletePetPathParams
	Headers    *DeletePetHeaders
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*DeletePetResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *DeletePetServiceRequestOptions) Validate() error {
	return nil
}

// DeletePetResponseData is what DeletePet returns.
type DeletePetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewDeletePetResponseData200 returns the 200 response.
func NewDeletePetResponseData200() *DeletePetResponseData {
	return &DeletePetResponseData{Status: 200, contentType: ""}
}

// NewDeletePetResponseData400 returns the 400 response.
func NewDeletePetResponseData400() *DeletePetResponseData {
	return &DeletePetResponseData{Status: 400, contentType: ""}
}

// NewDeletePetResponseDataDefault returns the default response.
func NewDeletePetResponseDataDefault(status int) *DeletePetResponseData {
	return &DeletePetResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *DeletePetResponseData) WithStatus(code int) *DeletePetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *DeletePetResponseData) WithHeaders(h http.Header) *DeletePetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *DeletePetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *DeletePetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *DeletePetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *DeletePetResponseData) ContentType() string {
	return r.contentType
}

// UploadFileServiceRequestOptions is what UploadFile receives.
type UploadFileServiceRequestOptions struct {
	PathParams *UploadFilePathParams
	Query      *UploadFileQuery
	// Body sent as application/octet-stream.
	Body *UploadFileRequestBody
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*UploadFileResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *UploadFileServiceRequestOptions) Validate() error {
	return nil
}

// UploadFileResponseData is what UploadFile returns.
type UploadFileResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewUploadFileResponseData200 returns the 200 response with its application/json body.
func NewUploadFileResponseData200(body *APIResponse) *UploadFileResponseData {
	return &UploadFileResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewUploadFileResponseData400 returns the 400 response.
func NewUploadFileResponseData400() *UploadFileResponseData {
	return &UploadFileResponseData{Status: 400, contentType: ""}
}

// NewUploadFileResponseData404 returns the 404 response.
func NewUploadFileResponseData404() *UploadFileResponseData {
	return &UploadFileResponseData{Status: 404, contentType: ""}
}

// NewUploadFileResponseDataDefault returns the default response.
func NewUploadFileResponseDataDefault(status int) *UploadFileResponseData {
	return &UploadFileResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *UploadFileResponseData) WithStatus(code int) *UploadFileResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *UploadFileResponseData) WithHeaders(h http.Header) *UploadFileResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *UploadFileResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *UploadFileResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *UploadFileResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *UploadFileResponseData) ContentType() string {
	return r.contentType
}

// GetInventoryServiceRequestOptions is what GetInventory receives.
type GetInventoryServiceRequestOptions struct {
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetInventoryResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetInventoryServiceRequestOptions) Validate() error {
	return nil
}

// GetInventoryResponseData is what GetInventory returns.
type GetInventoryResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetInventoryResponseData200 returns the 200 response with its application/json body.
func NewGetInventoryResponseData200(body GetInventoryResponse200) *GetInventoryResponseData {
	return &GetInventoryResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewGetInventoryResponseDataDefault returns the default response.
func NewGetInventoryResponseDataDefault(status int) *GetInventoryResponseData {
	return &GetInventoryResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *GetInventoryResponseData) WithStatus(code int) *GetInventoryResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetInventoryResponseData) WithHeaders(h http.Header) *GetInventoryResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetInventoryResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetInventoryResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetInventoryResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetInventoryResponseData) ContentType() string {
	return r.contentType
}

// PlaceOrderServiceRequestOptions is what PlaceOrder receives.
type PlaceOrderServiceRequestOptions struct {
	// Body sent as application/json.
	BodyJSON *Order
	// Body sent as application/xml.
	BodyXML *Order
	// Body sent as application/x-www-form-urlencoded.
	BodyForm *Order
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*PlaceOrderResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PlaceOrderServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.BodyJSON != nil {
		errs.Append("body", o.BodyJSON.Validate())
	}
	if o.BodyXML != nil {
		errs.Append("body", o.BodyXML.Validate())
	}
	if o.BodyForm != nil {
		errs.Append("body", o.BodyForm.Validate())
	}
	return errs.Err()
}

// PlaceOrderResponseData is what PlaceOrder returns.
type PlaceOrderResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPlaceOrderResponseData200 returns the 200 response with its application/json body.
func NewPlaceOrderResponseData200(body *Order) *PlaceOrderResponseData {
	return &PlaceOrderResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewPlaceOrderResponseData400 returns the 400 response.
func NewPlaceOrderResponseData400() *PlaceOrderResponseData {
	return &PlaceOrderResponseData{Status: 400, contentType: ""}
}

// NewPlaceOrderResponseData422 returns the 422 response.
func NewPlaceOrderResponseData422() *PlaceOrderResponseData {
	return &PlaceOrderResponseData{Status: 422, contentType: ""}
}

// NewPlaceOrderResponseDataDefault returns the default response.
func NewPlaceOrderResponseDataDefault(status int) *PlaceOrderResponseData {
	return &PlaceOrderResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *PlaceOrderResponseData) WithStatus(code int) *PlaceOrderResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PlaceOrderResponseData) WithHeaders(h http.Header) *PlaceOrderResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PlaceOrderResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PlaceOrderResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PlaceOrderResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PlaceOrderResponseData) ContentType() string {
	return r.contentType
}

// GetOrderByIDServiceRequestOptions is what GetOrderByID receives.
type GetOrderByIDServiceRequestOptions struct {
	PathParams *GetOrderByIDPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetOrderByIDResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetOrderByIDServiceRequestOptions) Validate() error {
	return nil
}

// GetOrderByIDResponseData is what GetOrderByID returns.
type GetOrderByIDResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetOrderByIDResponseData200 returns the 200 response with its application/json body.
func NewGetOrderByIDResponseData200(body *Order) *GetOrderByIDResponseData {
	return &GetOrderByIDResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewGetOrderByIDResponseData400 returns the 400 response.
func NewGetOrderByIDResponseData400() *GetOrderByIDResponseData {
	return &GetOrderByIDResponseData{Status: 400, contentType: ""}
}

// NewGetOrderByIDResponseData404 returns the 404 response.
func NewGetOrderByIDResponseData404() *GetOrderByIDResponseData {
	return &GetOrderByIDResponseData{Status: 404, contentType: ""}
}

// NewGetOrderByIDResponseDataDefault returns the default response.
func NewGetOrderByIDResponseDataDefault(status int) *GetOrderByIDResponseData {
	return &GetOrderByIDResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *GetOrderByIDResponseData) WithStatus(code int) *GetOrderByIDResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetOrderByIDResponseData) WithHeaders(h http.Header) *GetOrderByIDResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetOrderByIDResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetOrderByIDResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetOrderByIDResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetOrderByIDResponseData) ContentType() string {
	return r.contentType
}

// DeleteOrderServiceRequestOptions is what DeleteOrder receives.
type DeleteOrderServiceRequestOptions struct {
	PathParams *DeleteOrderPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*DeleteOrderResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *DeleteOrderServiceRequestOptions) Validate() error {
	return nil
}

// DeleteOrderResponseData is what DeleteOrder returns.
type DeleteOrderResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewDeleteOrderResponseData200 returns the 200 response.
func NewDeleteOrderResponseData200() *DeleteOrderResponseData {
	return &DeleteOrderResponseData{Status: 200, contentType: ""}
}

// NewDeleteOrderResponseData400 returns the 400 response.
func NewDeleteOrderResponseData400() *DeleteOrderResponseData {
	return &DeleteOrderResponseData{Status: 400, contentType: ""}
}

// NewDeleteOrderResponseData404 returns the 404 response.
func NewDeleteOrderResponseData404() *DeleteOrderResponseData {
	return &DeleteOrderResponseData{Status: 404, contentType: ""}
}

// NewDeleteOrderResponseDataDefault returns the default response.
func NewDeleteOrderResponseDataDefault(status int) *DeleteOrderResponseData {
	return &DeleteOrderResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *DeleteOrderResponseData) WithStatus(code int) *DeleteOrderResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *DeleteOrderResponseData) WithHeaders(h http.Header) *DeleteOrderResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *DeleteOrderResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *DeleteOrderResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *DeleteOrderResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *DeleteOrderResponseData) ContentType() string {
	return r.contentType
}

// CreateUserServiceRequestOptions is what CreateUser receives.
type CreateUserServiceRequestOptions struct {
	// Body sent as application/json.
	BodyJSON *User
	// Body sent as application/xml.
	BodyXML *User
	// Body sent as application/x-www-form-urlencoded.
	BodyForm *User
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*CreateUserResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *CreateUserServiceRequestOptions) Validate() error {
	return nil
}

// CreateUserResponseData is what CreateUser returns.
type CreateUserResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewCreateUserResponseData200 returns the 200 response with its application/json body.
func NewCreateUserResponseData200(body *User) *CreateUserResponseData {
	return &CreateUserResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewCreateUserResponseDataDefault returns the default response.
func NewCreateUserResponseDataDefault(status int) *CreateUserResponseData {
	return &CreateUserResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *CreateUserResponseData) WithStatus(code int) *CreateUserResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *CreateUserResponseData) WithHeaders(h http.Header) *CreateUserResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *CreateUserResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *CreateUserResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *CreateUserResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *CreateUserResponseData) ContentType() string {
	return r.contentType
}

// CreateUsersWithListInputServiceRequestOptions is what CreateUsersWithListInput receives.
type CreateUsersWithListInputServiceRequestOptions struct {
	// Body sent as application/json.
	Body CreateUsersWithListInputRequestBody
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*CreateUsersWithListInputResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *CreateUsersWithListInputServiceRequestOptions) Validate() error {
	return nil
}

// CreateUsersWithListInputResponseData is what CreateUsersWithListInput returns.
type CreateUsersWithListInputResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewCreateUsersWithListInputResponseData200 returns the 200 response with its application/json body.
func NewCreateUsersWithListInputResponseData200(body *User) *CreateUsersWithListInputResponseData {
	return &CreateUsersWithListInputResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewCreateUsersWithListInputResponseDataDefault returns the default response.
func NewCreateUsersWithListInputResponseDataDefault(status int) *CreateUsersWithListInputResponseData {
	return &CreateUsersWithListInputResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *CreateUsersWithListInputResponseData) WithStatus(code int) *CreateUsersWithListInputResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *CreateUsersWithListInputResponseData) WithHeaders(h http.Header) *CreateUsersWithListInputResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *CreateUsersWithListInputResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *CreateUsersWithListInputResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *CreateUsersWithListInputResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *CreateUsersWithListInputResponseData) ContentType() string {
	return r.contentType
}

// LoginUserServiceRequestOptions is what LoginUser receives.
type LoginUserServiceRequestOptions struct {
	Query *LoginUserQuery
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*LoginUserResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *LoginUserServiceRequestOptions) Validate() error {
	return nil
}

// LoginUserResponseData is what LoginUser returns.
type LoginUserResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewLoginUserResponseData200 returns the 200 response with its application/json body.
func NewLoginUserResponseData200(body *LoginUserJSONResponse200) *LoginUserResponseData {
	return &LoginUserResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewLoginUserResponseData400 returns the 400 response.
func NewLoginUserResponseData400() *LoginUserResponseData {
	return &LoginUserResponseData{Status: 400, contentType: ""}
}

// NewLoginUserResponseDataDefault returns the default response.
func NewLoginUserResponseDataDefault(status int) *LoginUserResponseData {
	return &LoginUserResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *LoginUserResponseData) WithStatus(code int) *LoginUserResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *LoginUserResponseData) WithHeaders(h http.Header) *LoginUserResponseData {
	r.Headers = h
	return r
}

// WithTypedHeaders adds the headers the spec declares for status 200.
func (r *LoginUserResponseData) WithTypedHeaders(h LoginUserResponse200Headers) *LoginUserResponseData {
	r.Headers = runtime.Headers(r.Headers, h)
	return r
}

// StatusCode returns the status.
func (r *LoginUserResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *LoginUserResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *LoginUserResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *LoginUserResponseData) ContentType() string {
	return r.contentType
}

// LogoutUserServiceRequestOptions is what LogoutUser receives.
type LogoutUserServiceRequestOptions struct {
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*LogoutUserResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *LogoutUserServiceRequestOptions) Validate() error {
	return nil
}

// LogoutUserResponseData is what LogoutUser returns.
type LogoutUserResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewLogoutUserResponseData200 returns the 200 response.
func NewLogoutUserResponseData200() *LogoutUserResponseData {
	return &LogoutUserResponseData{Status: 200, contentType: ""}
}

// NewLogoutUserResponseDataDefault returns the default response.
func NewLogoutUserResponseDataDefault(status int) *LogoutUserResponseData {
	return &LogoutUserResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *LogoutUserResponseData) WithStatus(code int) *LogoutUserResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *LogoutUserResponseData) WithHeaders(h http.Header) *LogoutUserResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *LogoutUserResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *LogoutUserResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *LogoutUserResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *LogoutUserResponseData) ContentType() string {
	return r.contentType
}

// GetUserByNameServiceRequestOptions is what GetUserByName receives.
type GetUserByNameServiceRequestOptions struct {
	PathParams *GetUserByNamePathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetUserByNameResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetUserByNameServiceRequestOptions) Validate() error {
	return nil
}

// GetUserByNameResponseData is what GetUserByName returns.
type GetUserByNameResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetUserByNameResponseData200 returns the 200 response with its application/json body.
func NewGetUserByNameResponseData200(body *User) *GetUserByNameResponseData {
	return &GetUserByNameResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewGetUserByNameResponseData400 returns the 400 response.
func NewGetUserByNameResponseData400() *GetUserByNameResponseData {
	return &GetUserByNameResponseData{Status: 400, contentType: ""}
}

// NewGetUserByNameResponseData404 returns the 404 response.
func NewGetUserByNameResponseData404() *GetUserByNameResponseData {
	return &GetUserByNameResponseData{Status: 404, contentType: ""}
}

// NewGetUserByNameResponseDataDefault returns the default response.
func NewGetUserByNameResponseDataDefault(status int) *GetUserByNameResponseData {
	return &GetUserByNameResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *GetUserByNameResponseData) WithStatus(code int) *GetUserByNameResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetUserByNameResponseData) WithHeaders(h http.Header) *GetUserByNameResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetUserByNameResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetUserByNameResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetUserByNameResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetUserByNameResponseData) ContentType() string {
	return r.contentType
}

// UpdateUserServiceRequestOptions is what UpdateUser receives.
type UpdateUserServiceRequestOptions struct {
	PathParams *UpdateUserPathParams
	// Body sent as application/json.
	BodyJSON *User
	// Body sent as application/xml.
	BodyXML *User
	// Body sent as application/x-www-form-urlencoded.
	BodyForm *User
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*UpdateUserResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *UpdateUserServiceRequestOptions) Validate() error {
	return nil
}

// UpdateUserResponseData is what UpdateUser returns.
type UpdateUserResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewUpdateUserResponseData200 returns the 200 response.
func NewUpdateUserResponseData200() *UpdateUserResponseData {
	return &UpdateUserResponseData{Status: 200, contentType: ""}
}

// NewUpdateUserResponseData400 returns the 400 response.
func NewUpdateUserResponseData400() *UpdateUserResponseData {
	return &UpdateUserResponseData{Status: 400, contentType: ""}
}

// NewUpdateUserResponseData404 returns the 404 response.
func NewUpdateUserResponseData404() *UpdateUserResponseData {
	return &UpdateUserResponseData{Status: 404, contentType: ""}
}

// NewUpdateUserResponseDataDefault returns the default response.
func NewUpdateUserResponseDataDefault(status int) *UpdateUserResponseData {
	return &UpdateUserResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *UpdateUserResponseData) WithStatus(code int) *UpdateUserResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *UpdateUserResponseData) WithHeaders(h http.Header) *UpdateUserResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *UpdateUserResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *UpdateUserResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *UpdateUserResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *UpdateUserResponseData) ContentType() string {
	return r.contentType
}

// DeleteUserServiceRequestOptions is what DeleteUser receives.
type DeleteUserServiceRequestOptions struct {
	PathParams *DeleteUserPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*DeleteUserResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *DeleteUserServiceRequestOptions) Validate() error {
	return nil
}

// DeleteUserResponseData is what DeleteUser returns.
type DeleteUserResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewDeleteUserResponseData200 returns the 200 response.
func NewDeleteUserResponseData200() *DeleteUserResponseData {
	return &DeleteUserResponseData{Status: 200, contentType: ""}
}

// NewDeleteUserResponseData400 returns the 400 response.
func NewDeleteUserResponseData400() *DeleteUserResponseData {
	return &DeleteUserResponseData{Status: 400, contentType: ""}
}

// NewDeleteUserResponseData404 returns the 404 response.
func NewDeleteUserResponseData404() *DeleteUserResponseData {
	return &DeleteUserResponseData{Status: 404, contentType: ""}
}

// NewDeleteUserResponseDataDefault returns the default response.
func NewDeleteUserResponseDataDefault(status int) *DeleteUserResponseData {
	return &DeleteUserResponseData{Status: status, contentType: ""}
}

// WithStatus sets the status code.
func (r *DeleteUserResponseData) WithStatus(code int) *DeleteUserResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *DeleteUserResponseData) WithHeaders(h http.Header) *DeleteUserResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *DeleteUserResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *DeleteUserResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *DeleteUserResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *DeleteUserResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = httpserver.ErrorKind
	HandlerError        = httpserver.HandlerError
	ErrorHandler        = httpserver.ErrorHandler
	ErrorHandlerFunc    = httpserver.ErrorHandlerFunc
	DefaultErrorHandler = httpserver.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = httpserver.ErrorParse
	ErrorDecode     = httpserver.ErrorDecode
	ErrorValidation = httpserver.ErrorValidation
	ErrorService    = httpserver.ErrorService
	ErrorResponse   = httpserver.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router              any
	Middleware          []func(http.Handler) http.Handler
	OperationMiddleware []func(http.Handler) http.Handler
	ErrorHandler        httpserver.ErrorHandler
	JSONDecoder         func(data []byte, v any) error
	JSONEncoder         func(v any) ([]byte, error)
	MultipartMaxMemory  int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       httpserver.DefaultErrorHandler{},
		JSONDecoder:        json.Unmarshal,
		JSONEncoder:        json.Marshal,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithOperationMiddleware wraps each operation with mw, once its name is on the context.
func WithOperationMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.OperationMiddleware = append(o.OperationMiddleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h httpserver.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON request bodies.
func WithJSONDecoder(decode func(data []byte, v any) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithJSONEncoder sets what writes JSON response bodies and stream frames.
func WithJSONEncoder(encode func(v any) ([]byte, error)) ServerOption {
	return func(o *ServerOptions) {
		o.JSONEncoder = encode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc        ServiceInterface
	opts       *ServerOptions
	operations httpserver.Chain
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	o := NewServerOptions(opts...)
	return &HTTPAdapter{svc: svc, opts: o, operations: httpserver.NewChain(o.OperationMiddleware...)}
}

// UpdatePet handles PUT /pet.
func (a *HTTPAdapter) UpdatePet(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "UpdatePet", a.serveUpdatePet)
}

func (a *HTTPAdapter) serveUpdatePet(w http.ResponseWriter, r *http.Request) {
	opts := &UpdatePetServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := runtime.DecodeJSON(r.Body, &opts.BodyJSON, true, a.opts.JSONDecoder); err != nil {
			a.failDecode(w, r, "UpdatePet", err)
			return
		}
	case "application/xml":
	case "application/x-www-form-urlencoded":
		if err := runtime.DecodeForm(r.Body, &opts.BodyForm, true, nil); err != nil {
			a.failDecode(w, r, "UpdatePet", err)
			return
		}
	case "":
		a.failDecode(w, r, "UpdatePet", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "UpdatePet", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.UpdatePet(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "UpdatePet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "UpdatePet", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "UpdatePet", res)
}

// AddPet handles POST /pet.
func (a *HTTPAdapter) AddPet(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "AddPet", a.serveAddPet)
}

func (a *HTTPAdapter) serveAddPet(w http.ResponseWriter, r *http.Request) {
	opts := &AddPetServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := runtime.DecodeJSON(r.Body, &opts.BodyJSON, true, a.opts.JSONDecoder); err != nil {
			a.failDecode(w, r, "AddPet", err)
			return
		}
	case "application/xml":
	case "application/x-www-form-urlencoded":
		if err := runtime.DecodeForm(r.Body, &opts.BodyForm, true, nil); err != nil {
			a.failDecode(w, r, "AddPet", err)
			return
		}
	case "":
		a.failDecode(w, r, "AddPet", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "AddPet", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.AddPet(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "AddPet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "AddPet", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "AddPet", res)
}

// FindPetsByStatus handles GET /pet/findByStatus.
func (a *HTTPAdapter) FindPetsByStatus(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "FindPetsByStatus", a.serveFindPetsByStatus)
}

func (a *HTTPAdapter) serveFindPetsByStatus(w http.ResponseWriter, r *http.Request) {
	opts := &FindPetsByStatusServiceRequestOptions{RawRequest: r}
	query := runtime.ParseQuery(r.URL.RawQuery)
	opts.Query = &FindPetsByStatusQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "status", Style: runtime.StyleForm, IsExplode: true, IsRequired: true, IsJSON: false}, &opts.Query.Status); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "FindPetsByStatus", ParamName: "status", ParamLocation: "query", Err: err})
		return
	}

	res, err := a.svc.FindPetsByStatus(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "FindPetsByStatus", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "FindPetsByStatus", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "FindPetsByStatus", res)
}

// FindPetsByTags handles GET /pet/findByTags.
func (a *HTTPAdapter) FindPetsByTags(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "FindPetsByTags", a.serveFindPetsByTags)
}

func (a *HTTPAdapter) serveFindPetsByTags(w http.ResponseWriter, r *http.Request) {
	opts := &FindPetsByTagsServiceRequestOptions{RawRequest: r}
	query := runtime.ParseQuery(r.URL.RawQuery)
	opts.Query = &FindPetsByTagsQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "tags", Style: runtime.StyleForm, IsExplode: true, IsRequired: true, IsJSON: false}, &opts.Query.Tags); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "FindPetsByTags", ParamName: "tags", ParamLocation: "query", Err: err})
		return
	}

	res, err := a.svc.FindPetsByTags(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "FindPetsByTags", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "FindPetsByTags", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "FindPetsByTags", res)
}

// GetPetByID handles GET /pet/{petId}.
func (a *HTTPAdapter) GetPetByID(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetPetByID", a.serveGetPetByID)
}

func (a *HTTPAdapter) serveGetPetByID(w http.ResponseWriter, r *http.Request) {
	opts := &GetPetByIDServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetPetByIDPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "petId")), runtime.Param{Name: "petId", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.PetID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetPetByID", ParamName: "petId", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetPetByID(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetPetByID", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetPetByID", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetPetByID", res)
}

// UpdatePetWithForm handles POST /pet/{petId}.
func (a *HTTPAdapter) UpdatePetWithForm(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "UpdatePetWithForm", a.serveUpdatePetWithForm)
}

func (a *HTTPAdapter) serveUpdatePetWithForm(w http.ResponseWriter, r *http.Request) {
	opts := &UpdatePetWithFormServiceRequestOptions{RawRequest: r}
	query := runtime.ParseQuery(r.URL.RawQuery)
	opts.PathParams = &UpdatePetWithFormPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "petId")), runtime.Param{Name: "petId", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.PetID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "UpdatePetWithForm", ParamName: "petId", ParamLocation: "path", Err: err})
		return
	}
	opts.Query = &UpdatePetWithFormQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "name", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Name); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "UpdatePetWithForm", ParamName: "name", ParamLocation: "query", Err: err})
		return
	}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "status", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Status); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "UpdatePetWithForm", ParamName: "status", ParamLocation: "query", Err: err})
		return
	}

	res, err := a.svc.UpdatePetWithForm(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "UpdatePetWithForm", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "UpdatePetWithForm", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "UpdatePetWithForm", res)
}

// DeletePet handles DELETE /pet/{petId}.
func (a *HTTPAdapter) DeletePet(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "DeletePet", a.serveDeletePet)
}

func (a *HTTPAdapter) serveDeletePet(w http.ResponseWriter, r *http.Request) {
	opts := &DeletePetServiceRequestOptions{RawRequest: r}
	opts.PathParams = &DeletePetPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "petId")), runtime.Param{Name: "petId", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.PetID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "DeletePet", ParamName: "petId", ParamLocation: "path", Err: err})
		return
	}
	opts.Headers = &DeletePetHeaders{}
	if err := runtime.DecodeHeader(r.Header, runtime.Param{Name: "api_key", Style: runtime.StyleSimple, IsExplode: false, IsRequired: false, IsJSON: false}, &opts.Headers.APIKey); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "DeletePet", ParamName: "api_key", ParamLocation: "header", Err: err})
		return
	}

	res, err := a.svc.DeletePet(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "DeletePet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "DeletePet", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "DeletePet", res)
}

// UploadFile handles POST /pet/{petId}/uploadImage.
func (a *HTTPAdapter) UploadFile(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "UploadFile", a.serveUploadFile)
}

func (a *HTTPAdapter) serveUploadFile(w http.ResponseWriter, r *http.Request) {
	opts := &UploadFileServiceRequestOptions{RawRequest: r}
	query := runtime.ParseQuery(r.URL.RawQuery)
	opts.PathParams = &UploadFilePathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "petId")), runtime.Param{Name: "petId", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.PetID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "UploadFile", ParamName: "petId", ParamLocation: "path", Err: err})
		return
	}
	opts.Query = &UploadFileQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "additionalMetadata", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.AdditionalMetadata); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "UploadFile", ParamName: "additionalMetadata", ParamLocation: "query", Err: err})
		return
	}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/octet-stream":
		file, err := runtime.DecodeFile(r, false)
		if err != nil {
			a.failDecode(w, r, "UploadFile", err)
			return
		}
		opts.Body = runtime.Ptr(UploadFileRequestBody(file))
	case "":
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "UploadFile", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.UploadFile(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "UploadFile", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "UploadFile", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "UploadFile", res)
}

// GetInventory handles GET /store/inventory.
func (a *HTTPAdapter) GetInventory(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetInventory", a.serveGetInventory)
}

func (a *HTTPAdapter) serveGetInventory(w http.ResponseWriter, r *http.Request) {
	opts := &GetInventoryServiceRequestOptions{RawRequest: r}

	res, err := a.svc.GetInventory(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetInventory", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetInventory", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetInventory", res)
}

// PlaceOrder handles POST /store/order.
func (a *HTTPAdapter) PlaceOrder(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "PlaceOrder", a.servePlaceOrder)
}

func (a *HTTPAdapter) servePlaceOrder(w http.ResponseWriter, r *http.Request) {
	opts := &PlaceOrderServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := runtime.DecodeJSON(r.Body, &opts.BodyJSON, false, a.opts.JSONDecoder); err != nil {
			a.failDecode(w, r, "PlaceOrder", err)
			return
		}
	case "application/xml":
	case "application/x-www-form-urlencoded":
		if err := runtime.DecodeForm(r.Body, &opts.BodyForm, false, nil); err != nil {
			a.failDecode(w, r, "PlaceOrder", err)
			return
		}
	case "":
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "PlaceOrder", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PlaceOrder(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PlaceOrder", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PlaceOrder", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "PlaceOrder", res)
}

// GetOrderByID handles GET /store/order/{orderId}.
func (a *HTTPAdapter) GetOrderByID(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetOrderByID", a.serveGetOrderByID)
}

func (a *HTTPAdapter) serveGetOrderByID(w http.ResponseWriter, r *http.Request) {
	opts := &GetOrderByIDServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetOrderByIDPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "orderId")), runtime.Param{Name: "orderId", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.OrderID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetOrderByID", ParamName: "orderId", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetOrderByID(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetOrderByID", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetOrderByID", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetOrderByID", res)
}

// DeleteOrder handles DELETE /store/order/{orderId}.
func (a *HTTPAdapter) DeleteOrder(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "DeleteOrder", a.serveDeleteOrder)
}

func (a *HTTPAdapter) serveDeleteOrder(w http.ResponseWriter, r *http.Request) {
	opts := &DeleteOrderServiceRequestOptions{RawRequest: r}
	opts.PathParams = &DeleteOrderPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "orderId")), runtime.Param{Name: "orderId", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.OrderID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "DeleteOrder", ParamName: "orderId", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.DeleteOrder(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "DeleteOrder", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "DeleteOrder", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "DeleteOrder", res)
}

// CreateUser handles POST /user.
func (a *HTTPAdapter) CreateUser(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "CreateUser", a.serveCreateUser)
}

func (a *HTTPAdapter) serveCreateUser(w http.ResponseWriter, r *http.Request) {
	opts := &CreateUserServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := runtime.DecodeJSON(r.Body, &opts.BodyJSON, false, a.opts.JSONDecoder); err != nil {
			a.failDecode(w, r, "CreateUser", err)
			return
		}
	case "application/xml":
	case "application/x-www-form-urlencoded":
		if err := runtime.DecodeForm(r.Body, &opts.BodyForm, false, nil); err != nil {
			a.failDecode(w, r, "CreateUser", err)
			return
		}
	case "":
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "CreateUser", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.CreateUser(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "CreateUser", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "CreateUser", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "CreateUser", res)
}

// CreateUsersWithListInput handles POST /user/createWithList.
func (a *HTTPAdapter) CreateUsersWithListInput(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "CreateUsersWithListInput", a.serveCreateUsersWithListInput)
}

func (a *HTTPAdapter) serveCreateUsersWithListInput(w http.ResponseWriter, r *http.Request) {
	opts := &CreateUsersWithListInputServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := runtime.DecodeJSON(r.Body, &opts.Body, false, a.opts.JSONDecoder); err != nil {
			a.failDecode(w, r, "CreateUsersWithListInput", err)
			return
		}
	case "":
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "CreateUsersWithListInput", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.CreateUsersWithListInput(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "CreateUsersWithListInput", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "CreateUsersWithListInput", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "CreateUsersWithListInput", res)
}

// LoginUser handles GET /user/login.
func (a *HTTPAdapter) LoginUser(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "LoginUser", a.serveLoginUser)
}

func (a *HTTPAdapter) serveLoginUser(w http.ResponseWriter, r *http.Request) {
	opts := &LoginUserServiceRequestOptions{RawRequest: r}
	query := runtime.ParseQuery(r.URL.RawQuery)
	opts.Query = &LoginUserQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "username", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Username); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "LoginUser", ParamName: "username", ParamLocation: "query", Err: err})
		return
	}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "password", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Password); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "LoginUser", ParamName: "password", ParamLocation: "query", Err: err})
		return
	}

	res, err := a.svc.LoginUser(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "LoginUser", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "LoginUser", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "LoginUser", res)
}

// LogoutUser handles GET /user/logout.
func (a *HTTPAdapter) LogoutUser(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "LogoutUser", a.serveLogoutUser)
}

func (a *HTTPAdapter) serveLogoutUser(w http.ResponseWriter, r *http.Request) {
	opts := &LogoutUserServiceRequestOptions{RawRequest: r}

	res, err := a.svc.LogoutUser(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "LogoutUser", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "LogoutUser", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "LogoutUser", res)
}

// GetUserByName handles GET /user/{username}.
func (a *HTTPAdapter) GetUserByName(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetUserByName", a.serveGetUserByName)
}

func (a *HTTPAdapter) serveGetUserByName(w http.ResponseWriter, r *http.Request) {
	opts := &GetUserByNameServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetUserByNamePathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "username")), runtime.Param{Name: "username", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.Username); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetUserByName", ParamName: "username", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetUserByName(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserByName", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserByName", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetUserByName", res)
}

// UpdateUser handles PUT /user/{username}.
func (a *HTTPAdapter) UpdateUser(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "UpdateUser", a.serveUpdateUser)
}

func (a *HTTPAdapter) serveUpdateUser(w http.ResponseWriter, r *http.Request) {
	opts := &UpdateUserServiceRequestOptions{RawRequest: r}
	opts.PathParams = &UpdateUserPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "username")), runtime.Param{Name: "username", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.Username); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "UpdateUser", ParamName: "username", ParamLocation: "path", Err: err})
		return
	}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := runtime.DecodeJSON(r.Body, &opts.BodyJSON, false, a.opts.JSONDecoder); err != nil {
			a.failDecode(w, r, "UpdateUser", err)
			return
		}
	case "application/xml":
	case "application/x-www-form-urlencoded":
		if err := runtime.DecodeForm(r.Body, &opts.BodyForm, false, nil); err != nil {
			a.failDecode(w, r, "UpdateUser", err)
			return
		}
	case "":
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "UpdateUser", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.UpdateUser(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "UpdateUser", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "UpdateUser", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "UpdateUser", res)
}

// DeleteUser handles DELETE /user/{username}.
func (a *HTTPAdapter) DeleteUser(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "DeleteUser", a.serveDeleteUser)
}

func (a *HTTPAdapter) serveDeleteUser(w http.ResponseWriter, r *http.Request) {
	opts := &DeleteUserServiceRequestOptions{RawRequest: r}
	opts.PathParams = &DeleteUserPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "username")), runtime.Param{Name: "username", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.Username); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "DeleteUser", ParamName: "username", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.DeleteUser(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "DeleteUser", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "DeleteUser", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "DeleteUser", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *httpserver.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := httpserver.Writer{Marshal: a.opts.JSONEncoder}.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Put("/pet", a.UpdatePet)
		r.Post("/pet", a.AddPet)
		r.Get("/pet/findByStatus", a.FindPetsByStatus)
		r.Get("/pet/findByTags", a.FindPetsByTags)
		r.Get("/pet/{petId}", a.GetPetByID)
		r.Post("/pet/{petId}", a.UpdatePetWithForm)
		r.Delete("/pet/{petId}", a.DeletePet)
		r.Post("/pet/{petId}/uploadImage", a.UploadFile)
		r.Get("/store/inventory", a.GetInventory)
		r.Post("/store/order", a.PlaceOrder)
		r.Get("/store/order/{orderId}", a.GetOrderByID)
		r.Delete("/store/order/{orderId}", a.DeleteOrder)
		r.Post("/user", a.CreateUser)
		r.Post("/user/createWithList", a.CreateUsersWithListInput)
		r.Get("/user/login", a.LoginUser)
		r.Get("/user/logout", a.LogoutUser)
		r.Get("/user/{username}", a.GetUserByName)
		r.Put("/user/{username}", a.UpdateUser)
		r.Delete("/user/{username}", a.DeleteUser)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
}
