# Optional global app settings: port, history, storage, branding.
# Drop this file if you're happy with the defaults.

port: 2200
homeURL: /

history:
  enabled: true
  duration: 1h

# storage:
#   type: redis
#   redis:
#     address: redis:6379
