package middleware

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"strings"

	"github.com/mockzilla/mockzilla/v2/pkg/config"
	validator "github.com/pb33f/libopenapi-validator"
	"github.com/pb33f/libopenapi-validator/errors"
)

// ValidatorSource yields the validator to use for the current request.
// Portable mode hot-reloads the spec; the source closes over a slot
// that the reload swaps so the middleware always picks up the validator
// built from the latest spec. Returning nil disables validation for
// this request (e.g. when the validator failed to build for the spec).
type ValidatorSource func() validator.Validator

// CreateValidationMiddleware returns middleware that validates incoming
// requests and outgoing responses against the OpenAPI document.
//
// Request validation runs before the handler. On failure the request is
// short-circuited with a 400 and a JSON body describing the failures.
//
// Response validation runs after the handler. The response writer is
// captured so the generated payload can be validated; on failure the
// captured body is discarded and a 500 is returned. When validation
// passes, the captured response is written through unchanged.
//
// Either check is skipped when the corresponding flag in the service
// config's validation block is false.
func CreateValidationMiddleware(params *Params, source ValidatorSource) func(http.Handler) http.Handler {
	log := params.Logger("validation")

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
			v := source()
			if v == nil {
				next.ServeHTTP(w, req)
				return
			}

			cfg := params.GetServiceConfig(req)
			validateReq := cfg == nil || cfg.Validate.RequestEnabled()
			validateResp := cfg == nil || cfg.Validate.ResponseEnabled()

			// Validator works against the OpenAPI spec's path space (no
			// service mount prefix). Build a sibling request with the
			// mount stripped from URL.Path so spec lookup matches.
			validatorReq := requestForValidator(req, cfg)

			if validateReq {
				body, restore, err := snapshotBody(req)
				if err != nil {
					RequestLog(log, req).Warn("Validation: failed to read request body", "error", err)
				} else {
					req.Body = restore
					validatorReq.Body = io.NopCloser(bytes.NewReader(body))
					if ok, validationErrs := v.ValidateHttpRequestSync(validatorReq); !ok {
						// "Path not found in spec" is a 404 condition,
						// not a 400. The downstream handler returns its
						// own 404; skip validation and let it through.
						if !allPathMissing(validationErrs) {
							writeValidationError(w, http.StatusBadRequest, "request validation failed", validationErrs)
							return
						}
					}
					req.Body = io.NopCloser(bytes.NewReader(body))
				}
			}

			if !validateResp {
				next.ServeHTTP(w, req)
				return
			}

			rw := &responseWriter{
				ResponseWriter: w,
				body:           new(bytes.Buffer),
				statusCode:     http.StatusOK,
			}
			next.ServeHTTP(rw, req)

			// Only validate successful responses. Non-2xx are typically
			// generated by middleware (error injection, upstream errors)
			// and their schemas often aren't declared in the spec.
			if rw.statusCode >= 200 && rw.statusCode < 300 {
				resp := &http.Response{
					StatusCode: rw.statusCode,
					Header:     rw.Header().Clone(),
					Body:       io.NopCloser(bytes.NewReader(rw.body.Bytes())),
				}
				if ok, validationErrs := v.ValidateHttpResponse(validatorReq, resp); !ok {
					// Schema-render failures (circular $ref chains the
					// validator can't unroll) are libopenapi-validator
					// limitations, not generator bugs. Log and let the
					// response through — our generator handles recursion.
					if allSchemaRenderFailure(validationErrs) {
						RequestLog(log, req).Warn("Validator schema render failed; skipping response validation",
							"method", req.Method,
							"path", req.URL.Path,
							"errors", len(validationErrs))
					} else {
						RequestLog(log, req).Warn("Response validation failed",
							"method", req.Method,
							"path", req.URL.Path,
							"errors", len(validationErrs))
						writeValidationError(w, http.StatusInternalServerError, "response validation failed", validationErrs)
						return
					}
				}
			}

			writeThrough(w, rw)
		})
	}
}

// requestForValidator returns a shallow clone of req with URL.Path
// rewritten to the spec-relative path (i.e. with the service mount
// prefix stripped). libopenapi-validator looks up paths in the spec
// verbatim, so a request to `/foo/bar/pets` against a spec that
// declares `/pets` mounted at `/foo/bar` must reach the validator as
// `/pets`. When cfg is nil or no prefix is configured, the request is
// returned with only URL and Body cloned (the body is rewritten by the
// caller).
func requestForValidator(req *http.Request, cfg *config.ServiceConfig) *http.Request {
	clone := req.Clone(req.Context())
	if cfg == nil {
		return clone
	}
	prefix := servicePrefix(cfg)
	if prefix == "" || prefix == "/" {
		return clone
	}
	cloneURL := *req.URL
	cloneURL.Path = stripPrefix(cloneURL.Path, prefix)
	if cloneURL.RawPath != "" {
		cloneURL.RawPath = stripPrefix(cloneURL.RawPath, prefix)
	}
	clone.URL = &cloneURL
	clone.RequestURI = ""
	return clone
}

// servicePrefix mirrors api.ServicePrefix without pulling in pkg/api
// (which would be a cyclic import). Logic must stay in lockstep.
func servicePrefix(cfg *config.ServiceConfig) string {
	if cfg.Mount != "" {
		if strings.HasPrefix(cfg.Mount, "/") {
			return cfg.Mount
		}
		return "/" + cfg.Mount
	}
	if cfg.Name == "" {
		return "/"
	}
	return "/" + cfg.Name
}

func stripPrefix(p, prefix string) string {
	p = strings.TrimSuffix(p, "/")
	prefix = strings.TrimSuffix(prefix, "/")
	if !strings.HasPrefix(p, prefix) {
		return p
	}
	stripped := strings.TrimPrefix(p, prefix)
	if stripped == "" {
		return "/"
	}
	if !strings.HasPrefix(stripped, "/") {
		// Prefix matched mid-segment; not a real mount hit. Leave path alone.
		return p
	}
	return stripped
}

// allPathMissing reports whether every validation failure is the
// "path/operation not declared in spec" kind. When true the middleware
// hands the request to the next handler so the handler's own 404 path
// wins; surfacing a 400 here would be wrong since the request itself
// wasn't malformed - the spec simply doesn't describe that endpoint.
func allPathMissing(errs []*errors.ValidationError) bool {
	if len(errs) == 0 {
		return false
	}
	for _, e := range errs {
		if e.ValidationType != "path" || e.ValidationSubType != "missing" {
			return false
		}
	}
	return true
}

// allSchemaRenderFailure reports whether every validation failure is a
// libopenapi-validator schema-rendering failure (typically caused by
// circular $ref chains the validator can't unroll). These aren't
// generator bugs — our mock body may well be fine — they're validator
// limitations. The middleware treats them as "validation skipped" rather
// than surfacing them as 500s to the client.
func allSchemaRenderFailure(errs []*errors.ValidationError) bool {
	if len(errs) == 0 {
		return false
	}
	for _, e := range errs {
		if !strings.Contains(e.Reason, "schema render failure") &&
			!strings.Contains(e.Message, "failed schema rendering") {
			return false
		}
	}
	return true
}

// snapshotBody reads the request body into memory and returns a fresh
// reader so the request can be validated and then handed unchanged to
// the next handler. Returns (nil, nil, nil) for empty bodies.
func snapshotBody(req *http.Request) ([]byte, io.ReadCloser, error) {
	if req.Body == nil || req.Body == http.NoBody {
		return nil, http.NoBody, nil
	}
	body, err := io.ReadAll(req.Body)
	_ = req.Body.Close()
	if err != nil {
		return nil, nil, err
	}
	return body, io.NopCloser(bytes.NewReader(body)), nil
}

// validationErrorPayload is the JSON shape returned to clients on a
// validation failure. Keep the surface small: a top-level message and
// a list of validation-error details from libopenapi-validator.
type validationErrorPayload struct {
	Error   string                    `json:"error"`
	Details []*errors.ValidationError `json:"details,omitempty"`
}

func writeValidationError(w http.ResponseWriter, status int, message string, validationErrs []*errors.ValidationError) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(validationErrorPayload{
		Error:   message,
		Details: validationErrs,
	})
}
