// Code generated by mockzilla-codegen. DO NOT EDIT.

package static

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpserver"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type PostFooBarQuery struct {
	Q *string `json:"q,omitempty"`
}

type PostFooBarRequestBody map[string]any

type PostFooBarResponse200 struct {
	Car *string `json:"car,omitempty"`
}

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// PostFooBar handles POST /foo/bar.
	PostFooBar(ctx context.Context, opts *PostFooBarServiceRequestOptions) (*PostFooBarResponseData, error)
}

// PostFooBarServiceRequestOptions is what PostFooBar receives.
type PostFooBarServiceRequestOptions struct {
	Query *PostFooBarQuery
	// Body sent as application/json.
	Body PostFooBarRequestBody
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*PostFooBarResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostFooBarServiceRequestOptions) Validate() error {
	return nil
}

// PostFooBarResponseData is what PostFooBar returns.
type PostFooBarResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostFooBarResponseData returns the 200 response with its application/json body.
func NewPostFooBarResponseData(body *PostFooBarResponse200) *PostFooBarResponseData {
	return &PostFooBarResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *PostFooBarResponseData) WithStatus(code int) *PostFooBarResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostFooBarResponseData) WithHeaders(h http.Header) *PostFooBarResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostFooBarResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostFooBarResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostFooBarResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostFooBarResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = httpserver.ErrorKind
	HandlerError        = httpserver.HandlerError
	ErrorHandler        = httpserver.ErrorHandler
	ErrorHandlerFunc    = httpserver.ErrorHandlerFunc
	DefaultErrorHandler = httpserver.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = httpserver.ErrorParse
	ErrorDecode     = httpserver.ErrorDecode
	ErrorValidation = httpserver.ErrorValidation
	ErrorService    = httpserver.ErrorService
	ErrorResponse   = httpserver.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router              any
	Middleware          []func(http.Handler) http.Handler
	OperationMiddleware []func(http.Handler) http.Handler
	ErrorHandler        httpserver.ErrorHandler
	JSONDecoder         func(data []byte, v any) error
	JSONEncoder         func(v any) ([]byte, error)
	MultipartMaxMemory  int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       httpserver.DefaultErrorHandler{},
		JSONDecoder:        json.Unmarshal,
		JSONEncoder:        json.Marshal,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithOperationMiddleware wraps each operation with mw, once its name is on the context.
func WithOperationMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.OperationMiddleware = append(o.OperationMiddleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h httpserver.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON request bodies.
func WithJSONDecoder(decode func(data []byte, v any) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithJSONEncoder sets what writes JSON response bodies and stream frames.
func WithJSONEncoder(encode func(v any) ([]byte, error)) ServerOption {
	return func(o *ServerOptions) {
		o.JSONEncoder = encode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc        ServiceInterface
	opts       *ServerOptions
	operations httpserver.Chain
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	o := NewServerOptions(opts...)
	return &HTTPAdapter{svc: svc, opts: o, operations: httpserver.NewChain(o.OperationMiddleware...)}
}

// PostFooBar handles POST /foo/bar.
func (a *HTTPAdapter) PostFooBar(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "PostFooBar", a.servePostFooBar)
}

func (a *HTTPAdapter) servePostFooBar(w http.ResponseWriter, r *http.Request) {
	opts := &PostFooBarServiceRequestOptions{RawRequest: r}
	query := runtime.ParseQuery(r.URL.RawQuery)
	opts.Query = &PostFooBarQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "q", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Q); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "PostFooBar", ParamName: "q", ParamLocation: "query", Err: err})
		return
	}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := runtime.DecodeJSON(r.Body, &opts.Body, false, a.opts.JSONDecoder); err != nil {
			a.failDecode(w, r, "PostFooBar", err)
			return
		}
	case "":
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "PostFooBar", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PostFooBar(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostFooBar", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostFooBar", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "PostFooBar", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *httpserver.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := httpserver.Writer{Marshal: a.opts.JSONEncoder}.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Post("/foo/bar", a.PostFooBar)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
}
