// Code generated by mockzilla-codegen. DO NOT EDIT.

package users

import (
	"context"
	"encoding/json"
	"errors"
	"iter"
	"net/http"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpserver"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type User struct {
	ID    *string `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type UserConfig struct {
	Theme         *string `json:"theme,omitempty"`
	Language      *string `json:"language,omitempty"`
	Notifications *bool   `json:"notifications,omitempty"`
}

type GetUserPathParams struct {
	ID string `json:"id"`
}

type GetUserAvatarPathParams struct {
	ID string `json:"id"`
}

type GetUserProfilePathParams struct {
	ID string `json:"id"`
}

type GetUserConfigPathParams struct {
	ID string `json:"id"`
}

type GetUserAPIDataPathParams struct {
	ID string `json:"id"`
}

type GetUserHalPathParams struct {
	ID string `json:"id"`
}

type GetUserProblemPathParams struct {
	ID string `json:"id"`
}

type GetUserPdfPathParams struct {
	ID string `json:"id"`
}

type ListUsersResponse200 []User

type GetUserAvatarResponse200 = runtime.File

type GetUserProfileResponse200 = string

type ExportUsersResponse200 = string

type StreamUsersResponseItem = string

type GetUserPdfResponse200 = runtime.File

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// ListUsers handles GET /users.
	ListUsers(ctx context.Context, opts *ListUsersServiceRequestOptions) (*ListUsersResponseData, error)
	// GetUser handles GET /users/{id}.
	GetUser(ctx context.Context, opts *GetUserServiceRequestOptions) (*GetUserResponseData, error)
	// GetUserAvatar handles GET /users/{id}/avatar.
	GetUserAvatar(ctx context.Context, opts *GetUserAvatarServiceRequestOptions) (*GetUserAvatarResponseData, error)
	// GetUserProfile handles GET /users/{id}/profile.
	GetUserProfile(ctx context.Context, opts *GetUserProfileServiceRequestOptions) (*GetUserProfileResponseData, error)
	// ExportUsers handles GET /users/export.
	ExportUsers(ctx context.Context, opts *ExportUsersServiceRequestOptions) (*ExportUsersResponseData, error)
	// GetUserConfig handles GET /users/{id}/config.
	GetUserConfig(ctx context.Context, opts *GetUserConfigServiceRequestOptions) (*GetUserConfigResponseData, error)
	// GetUserAPIData handles GET /users/{id}/api-data.
	GetUserAPIData(ctx context.Context, opts *GetUserAPIDataServiceRequestOptions) (*GetUserAPIDataResponseData, error)
	// GetUserHal handles GET /users/{id}/hal.
	GetUserHal(ctx context.Context, opts *GetUserHalServiceRequestOptions) (*GetUserHalResponseData, error)
	// GetUserProblem handles GET /users/{id}/problem.
	GetUserProblem(ctx context.Context, opts *GetUserProblemServiceRequestOptions) (*GetUserProblemResponseData, error)
	// StreamUsers handles GET /users/stream.
	StreamUsers(ctx context.Context, opts *StreamUsersServiceRequestOptions) (*StreamUsersResponseData, error)
	// GetUserPdf handles GET /users/{id}/pdf.
	GetUserPdf(ctx context.Context, opts *GetUserPdfServiceRequestOptions) (*GetUserPdfResponseData, error)
}

// ListUsersServiceRequestOptions is what ListUsers receives.
type ListUsersServiceRequestOptions struct {
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*ListUsersResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ListUsersServiceRequestOptions) Validate() error {
	return nil
}

// ListUsersResponseData is what ListUsers returns.
type ListUsersResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewListUsersResponseData returns the 200 response with its application/json body.
func NewListUsersResponseData(body ListUsersResponse200) *ListUsersResponseData {
	return &ListUsersResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *ListUsersResponseData) WithStatus(code int) *ListUsersResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *ListUsersResponseData) WithHeaders(h http.Header) *ListUsersResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *ListUsersResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *ListUsersResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *ListUsersResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *ListUsersResponseData) ContentType() string {
	return r.contentType
}

// GetUserServiceRequestOptions is what GetUser receives.
type GetUserServiceRequestOptions struct {
	PathParams *GetUserPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetUserResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetUserServiceRequestOptions) Validate() error {
	return nil
}

// GetUserResponseData is what GetUser returns.
type GetUserResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetUserResponseData returns the 200 response with its application/json; charset=utf-8 body.
func NewGetUserResponseData(body *User) *GetUserResponseData {
	return &GetUserResponseData{Status: 200, Body: body, contentType: "application/json; charset=utf-8"}
}

// WithStatus sets the status code.
func (r *GetUserResponseData) WithStatus(code int) *GetUserResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetUserResponseData) WithHeaders(h http.Header) *GetUserResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetUserResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetUserResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetUserResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetUserResponseData) ContentType() string {
	return r.contentType
}

// GetUserAvatarServiceRequestOptions is what GetUserAvatar receives.
type GetUserAvatarServiceRequestOptions struct {
	PathParams *GetUserAvatarPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetUserAvatarResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetUserAvatarServiceRequestOptions) Validate() error {
	return nil
}

// GetUserAvatarResponseData is what GetUserAvatar returns.
type GetUserAvatarResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetUserAvatarResponseData returns the 200 response with its image/png body.
func NewGetUserAvatarResponseData(body *GetUserAvatarResponse200) *GetUserAvatarResponseData {
	return &GetUserAvatarResponseData{Status: 200, Body: body, contentType: "image/png"}
}

// WithStatus sets the status code.
func (r *GetUserAvatarResponseData) WithStatus(code int) *GetUserAvatarResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetUserAvatarResponseData) WithHeaders(h http.Header) *GetUserAvatarResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetUserAvatarResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetUserAvatarResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetUserAvatarResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetUserAvatarResponseData) ContentType() string {
	return r.contentType
}

// GetUserProfileServiceRequestOptions is what GetUserProfile receives.
type GetUserProfileServiceRequestOptions struct {
	PathParams *GetUserProfilePathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetUserProfileResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetUserProfileServiceRequestOptions) Validate() error {
	return nil
}

// GetUserProfileResponseData is what GetUserProfile returns.
type GetUserProfileResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetUserProfileResponseData returns the 200 response with its text/html; charset=utf-8 body.
func NewGetUserProfileResponseData(body *GetUserProfileResponse200) *GetUserProfileResponseData {
	return &GetUserProfileResponseData{Status: 200, Body: body, contentType: "text/html; charset=utf-8"}
}

// WithStatus sets the status code.
func (r *GetUserProfileResponseData) WithStatus(code int) *GetUserProfileResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetUserProfileResponseData) WithHeaders(h http.Header) *GetUserProfileResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetUserProfileResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetUserProfileResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetUserProfileResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetUserProfileResponseData) ContentType() string {
	return r.contentType
}

// ExportUsersServiceRequestOptions is what ExportUsers receives.
type ExportUsersServiceRequestOptions struct {
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*ExportUsersResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ExportUsersServiceRequestOptions) Validate() error {
	return nil
}

// ExportUsersResponseData is what ExportUsers returns.
type ExportUsersResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewExportUsersResponseData returns the 200 response with its text/csv body.
func NewExportUsersResponseData(body *ExportUsersResponse200) *ExportUsersResponseData {
	return &ExportUsersResponseData{Status: 200, Body: body, contentType: "text/csv"}
}

// WithStatus sets the status code.
func (r *ExportUsersResponseData) WithStatus(code int) *ExportUsersResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *ExportUsersResponseData) WithHeaders(h http.Header) *ExportUsersResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *ExportUsersResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *ExportUsersResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *ExportUsersResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *ExportUsersResponseData) ContentType() string {
	return r.contentType
}

// GetUserConfigServiceRequestOptions is what GetUserConfig receives.
type GetUserConfigServiceRequestOptions struct {
	PathParams *GetUserConfigPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetUserConfigResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetUserConfigServiceRequestOptions) Validate() error {
	return nil
}

// GetUserConfigResponseData is what GetUserConfig returns.
type GetUserConfigResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetUserConfigResponseData returns the 200 response with its application/xml body.
func NewGetUserConfigResponseData(body *UserConfig) *GetUserConfigResponseData {
	return &GetUserConfigResponseData{Status: 200, Body: body, contentType: "application/xml"}
}

// WithStatus sets the status code.
func (r *GetUserConfigResponseData) WithStatus(code int) *GetUserConfigResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetUserConfigResponseData) WithHeaders(h http.Header) *GetUserConfigResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetUserConfigResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetUserConfigResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetUserConfigResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetUserConfigResponseData) ContentType() string {
	return r.contentType
}

// GetUserAPIDataServiceRequestOptions is what GetUserAPIData receives.
type GetUserAPIDataServiceRequestOptions struct {
	PathParams *GetUserAPIDataPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetUserAPIDataResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetUserAPIDataServiceRequestOptions) Validate() error {
	return nil
}

// GetUserAPIDataResponseData is what GetUserAPIData returns.
type GetUserAPIDataResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetUserAPIDataResponseData returns the 200 response with its application/vnd.api+json body.
func NewGetUserAPIDataResponseData(body *User) *GetUserAPIDataResponseData {
	return &GetUserAPIDataResponseData{Status: 200, Body: body, contentType: "application/vnd.api+json"}
}

// WithStatus sets the status code.
func (r *GetUserAPIDataResponseData) WithStatus(code int) *GetUserAPIDataResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetUserAPIDataResponseData) WithHeaders(h http.Header) *GetUserAPIDataResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetUserAPIDataResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetUserAPIDataResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetUserAPIDataResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetUserAPIDataResponseData) ContentType() string {
	return r.contentType
}

// GetUserHalServiceRequestOptions is what GetUserHal receives.
type GetUserHalServiceRequestOptions struct {
	PathParams *GetUserHalPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetUserHalResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetUserHalServiceRequestOptions) Validate() error {
	return nil
}

// GetUserHalResponseData is what GetUserHal returns.
type GetUserHalResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetUserHalResponseData returns the 200 response with its application/hal+json body.
func NewGetUserHalResponseData(body *User) *GetUserHalResponseData {
	return &GetUserHalResponseData{Status: 200, Body: body, contentType: "application/hal+json"}
}

// WithStatus sets the status code.
func (r *GetUserHalResponseData) WithStatus(code int) *GetUserHalResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetUserHalResponseData) WithHeaders(h http.Header) *GetUserHalResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetUserHalResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetUserHalResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetUserHalResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetUserHalResponseData) ContentType() string {
	return r.contentType
}

// GetUserProblemServiceRequestOptions is what GetUserProblem receives.
type GetUserProblemServiceRequestOptions struct {
	PathParams *GetUserProblemPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetUserProblemResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetUserProblemServiceRequestOptions) Validate() error {
	return nil
}

// GetUserProblemResponseData is what GetUserProblem returns.
type GetUserProblemResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetUserProblemResponseData returns the 200 response with its application/problem+json body.
func NewGetUserProblemResponseData(body *User) *GetUserProblemResponseData {
	return &GetUserProblemResponseData{Status: 200, Body: body, contentType: "application/problem+json"}
}

// WithStatus sets the status code.
func (r *GetUserProblemResponseData) WithStatus(code int) *GetUserProblemResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetUserProblemResponseData) WithHeaders(h http.Header) *GetUserProblemResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetUserProblemResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetUserProblemResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetUserProblemResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetUserProblemResponseData) ContentType() string {
	return r.contentType
}

// StreamUsersServiceRequestOptions is what StreamUsers receives.
type StreamUsersServiceRequestOptions struct {
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*StreamUsersResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *StreamUsersServiceRequestOptions) Validate() error {
	return nil
}

// StreamUsersResponseData is what StreamUsers returns.
type StreamUsersResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewStreamUsersResponseData returns the 200 response that streams frames as application/x-ndjson.
func NewStreamUsersResponseData(frames iter.Seq[[]byte]) *StreamUsersResponseData {
	return &StreamUsersResponseData{Status: 200, Body: frames, contentType: "application/x-ndjson"}
}

// WithStatus sets the status code.
func (r *StreamUsersResponseData) WithStatus(code int) *StreamUsersResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *StreamUsersResponseData) WithHeaders(h http.Header) *StreamUsersResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *StreamUsersResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *StreamUsersResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *StreamUsersResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *StreamUsersResponseData) ContentType() string {
	return r.contentType
}

// GetUserPdfServiceRequestOptions is what GetUserPdf receives.
type GetUserPdfServiceRequestOptions struct {
	PathParams *GetUserPdfPathParams
	// GenerateResponse makes a mock response that satisfies the spec.
	GenerateResponse func() (*GetUserPdfResponseData, error)
	RawRequest       *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetUserPdfServiceRequestOptions) Validate() error {
	return nil
}

// GetUserPdfResponseData is what GetUserPdf returns.
type GetUserPdfResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetUserPdfResponseData returns the 200 response with its application/pdf body.
func NewGetUserPdfResponseData(body *GetUserPdfResponse200) *GetUserPdfResponseData {
	return &GetUserPdfResponseData{Status: 200, Body: body, contentType: "application/pdf"}
}

// WithStatus sets the status code.
func (r *GetUserPdfResponseData) WithStatus(code int) *GetUserPdfResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetUserPdfResponseData) WithHeaders(h http.Header) *GetUserPdfResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetUserPdfResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetUserPdfResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetUserPdfResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetUserPdfResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = httpserver.ErrorKind
	HandlerError        = httpserver.HandlerError
	ErrorHandler        = httpserver.ErrorHandler
	ErrorHandlerFunc    = httpserver.ErrorHandlerFunc
	DefaultErrorHandler = httpserver.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = httpserver.ErrorParse
	ErrorDecode     = httpserver.ErrorDecode
	ErrorValidation = httpserver.ErrorValidation
	ErrorService    = httpserver.ErrorService
	ErrorResponse   = httpserver.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router              any
	Middleware          []func(http.Handler) http.Handler
	OperationMiddleware []func(http.Handler) http.Handler
	ErrorHandler        httpserver.ErrorHandler
	JSONDecoder         func(data []byte, v any) error
	JSONEncoder         func(v any) ([]byte, error)
	MultipartMaxMemory  int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       httpserver.DefaultErrorHandler{},
		JSONDecoder:        json.Unmarshal,
		JSONEncoder:        json.Marshal,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithOperationMiddleware wraps each operation with mw, once its name is on the context.
func WithOperationMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.OperationMiddleware = append(o.OperationMiddleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h httpserver.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON request bodies.
func WithJSONDecoder(decode func(data []byte, v any) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithJSONEncoder sets what writes JSON response bodies and stream frames.
func WithJSONEncoder(encode func(v any) ([]byte, error)) ServerOption {
	return func(o *ServerOptions) {
		o.JSONEncoder = encode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc        ServiceInterface
	opts       *ServerOptions
	operations httpserver.Chain
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	o := NewServerOptions(opts...)
	return &HTTPAdapter{svc: svc, opts: o, operations: httpserver.NewChain(o.OperationMiddleware...)}
}

// ListUsers handles GET /users.
func (a *HTTPAdapter) ListUsers(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "ListUsers", a.serveListUsers)
}

func (a *HTTPAdapter) serveListUsers(w http.ResponseWriter, r *http.Request) {
	opts := &ListUsersServiceRequestOptions{RawRequest: r}

	res, err := a.svc.ListUsers(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "ListUsers", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "ListUsers", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "ListUsers", res)
}

// GetUser handles GET /users/{id}.
func (a *HTTPAdapter) GetUser(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetUser", a.serveGetUser)
}

func (a *HTTPAdapter) serveGetUser(w http.ResponseWriter, r *http.Request) {
	opts := &GetUserServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetUserPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetUser", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetUser(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUser", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUser", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetUser", res)
}

// GetUserAvatar handles GET /users/{id}/avatar.
func (a *HTTPAdapter) GetUserAvatar(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetUserAvatar", a.serveGetUserAvatar)
}

func (a *HTTPAdapter) serveGetUserAvatar(w http.ResponseWriter, r *http.Request) {
	opts := &GetUserAvatarServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetUserAvatarPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetUserAvatar", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetUserAvatar(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserAvatar", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserAvatar", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetUserAvatar", res)
}

// GetUserProfile handles GET /users/{id}/profile.
func (a *HTTPAdapter) GetUserProfile(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetUserProfile", a.serveGetUserProfile)
}

func (a *HTTPAdapter) serveGetUserProfile(w http.ResponseWriter, r *http.Request) {
	opts := &GetUserProfileServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetUserProfilePathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetUserProfile", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetUserProfile(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserProfile", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserProfile", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetUserProfile", res)
}

// ExportUsers handles GET /users/export.
func (a *HTTPAdapter) ExportUsers(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "ExportUsers", a.serveExportUsers)
}

func (a *HTTPAdapter) serveExportUsers(w http.ResponseWriter, r *http.Request) {
	opts := &ExportUsersServiceRequestOptions{RawRequest: r}

	res, err := a.svc.ExportUsers(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "ExportUsers", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "ExportUsers", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "ExportUsers", res)
}

// GetUserConfig handles GET /users/{id}/config.
func (a *HTTPAdapter) GetUserConfig(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetUserConfig", a.serveGetUserConfig)
}

func (a *HTTPAdapter) serveGetUserConfig(w http.ResponseWriter, r *http.Request) {
	opts := &GetUserConfigServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetUserConfigPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetUserConfig", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetUserConfig(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserConfig", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserConfig", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetUserConfig", res)
}

// GetUserAPIData handles GET /users/{id}/api-data.
func (a *HTTPAdapter) GetUserAPIData(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetUserAPIData", a.serveGetUserAPIData)
}

func (a *HTTPAdapter) serveGetUserAPIData(w http.ResponseWriter, r *http.Request) {
	opts := &GetUserAPIDataServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetUserAPIDataPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetUserAPIData", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetUserAPIData(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserAPIData", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserAPIData", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetUserAPIData", res)
}

// GetUserHal handles GET /users/{id}/hal.
func (a *HTTPAdapter) GetUserHal(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetUserHal", a.serveGetUserHal)
}

func (a *HTTPAdapter) serveGetUserHal(w http.ResponseWriter, r *http.Request) {
	opts := &GetUserHalServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetUserHalPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetUserHal", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetUserHal(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserHal", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserHal", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetUserHal", res)
}

// GetUserProblem handles GET /users/{id}/problem.
func (a *HTTPAdapter) GetUserProblem(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetUserProblem", a.serveGetUserProblem)
}

func (a *HTTPAdapter) serveGetUserProblem(w http.ResponseWriter, r *http.Request) {
	opts := &GetUserProblemServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetUserProblemPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetUserProblem", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetUserProblem(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserProblem", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserProblem", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetUserProblem", res)
}

// StreamUsers handles GET /users/stream.
func (a *HTTPAdapter) StreamUsers(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "StreamUsers", a.serveStreamUsers)
}

func (a *HTTPAdapter) serveStreamUsers(w http.ResponseWriter, r *http.Request) {
	opts := &StreamUsersServiceRequestOptions{RawRequest: r}

	res, err := a.svc.StreamUsers(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "StreamUsers", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "StreamUsers", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "StreamUsers", res)
}

// GetUserPdf handles GET /users/{id}/pdf.
func (a *HTTPAdapter) GetUserPdf(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetUserPdf", a.serveGetUserPdf)
}

func (a *HTTPAdapter) serveGetUserPdf(w http.ResponseWriter, r *http.Request) {
	opts := &GetUserPdfServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetUserPdfPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetUserPdf", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetUserPdf(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserPdf", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetUserPdf", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetUserPdf", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *httpserver.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := httpserver.Writer{Marshal: a.opts.JSONEncoder}.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Get("/users", a.ListUsers)
		r.Get("/users/{id}", a.GetUser)
		r.Get("/users/{id}/avatar", a.GetUserAvatar)
		r.Get("/users/{id}/profile", a.GetUserProfile)
		r.Get("/users/export", a.ExportUsers)
		r.Get("/users/{id}/config", a.GetUserConfig)
		r.Get("/users/{id}/api-data", a.GetUserAPIData)
		r.Get("/users/{id}/hal", a.GetUserHal)
		r.Get("/users/{id}/problem", a.GetUserProblem)
		r.Get("/users/stream", a.StreamUsers)
		r.Get("/users/{id}/pdf", a.GetUserPdf)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
}
