// Code generated by mockzilla-codegen. DO NOT EDIT.

package users

import (
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"sync"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla/v2/pkg/api"
	"github.com/mockzilla/mockzilla/v2/pkg/config"
	"github.com/mockzilla/mockzilla/v2/pkg/db"
	"github.com/mockzilla/mockzilla/v2/pkg/factory"
	"github.com/mockzilla/mockzilla/v2/pkg/generator"
	"github.com/mockzilla/mockzilla/v2/pkg/loader"
	"github.com/mockzilla/mockzilla/v2/pkg/schema"
	"github.com/mockzilla/mockzilla/v2/pkg/typedef"
)

//go:embed setup/config.yml
var configSrc []byte

//go:embed setup/openapi.*
var openapiSpecFS embed.FS

//go:embed setup/context.yml
var contextSrc []byte

// ServiceErrorHandler answers the requests that fail before the service is reached.
var ServiceErrorHandler ErrorHandler = DefaultErrorHandler{}

// cfg is set before any init function runs, so the package's other files can read it in theirs.
var cfg, cfgErr = config.NewServiceConfigFromBytes(configSrc)

func init() {
	if cfgErr != nil {
		slog.Error("Failed to parse service config", "error", cfgErr)
		return
	}
	loader.Register(cfg.Name, RegisterAPIRouter)
}

// RegisterAPIRouter registers the service with the central router.
func RegisterAPIRouter(router *api.Router) {
	serviceName := cfg.Name

	openapiSpec, err := api.ReadEmbeddedSpec(openapiSpecFS)
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to read OpenAPI spec for %s", serviceName), "error", err, "service", serviceName)
		return
	}

	registry, err := typedef.NewRegistry(openapiSpec, typedef.RegistryOptions{
		SpecOptions:     cfg.SpecOptions,
		ReleaseDocument: true,
	})
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to create registry for %s", serviceName), "error", err, "service", serviceName)
		return
	}

	orderedCtx := router.ServiceContext(serviceName, contextSrc)
	gen, err := generator.NewGenerator(orderedCtx, router.GetContexts())
	if err != nil {
		slog.Error(fmt.Sprintf("Failed to create generator for %s", serviceName), "error", err, "service", serviceName)
		return
	}

	router.RegisterHTTPHandler(cfg, func(serviceDB db.DB) api.Handler {
		userSvc := newService(&api.ServiceParams{
			AppConfig:     router.Config(),
			ServiceConfig: cfg,
			DB:            serviceDB,
		})
		genSvc := &generatorService{service: userSvc, generator: gen, registry: registry}
		return newServiceHandler(genSvc, gen, registry)
	}, api.WithMiddleware(getMiddleware()))

	slog.Info(fmt.Sprintf("Registered %s service", serviceName), "service", serviceName)
}

type serviceHandler struct {
	router   chi.Router
	gen      generator.Generate
	registry typedef.OperationRegistry
}

func newServiceHandler(svc ServiceInterface, gen generator.Generate, registry typedef.OperationRegistry) api.Handler {
	return &serviceHandler{
		router: NewRouter(svc,
			WithMiddleware(api.ContextReplacementsMiddleware),
			WithErrorHandler(returnedErrors{next: ServiceErrorHandler}),
		),
		gen:      gen,
		registry: registry,
	}
}

func (h *serviceHandler) Routes() api.RouteDescriptions {
	routes := h.router.Routes()
	descriptions := make(api.RouteDescriptions, 0, len(routes))
	for _, route := range routes {
		for method := range route.Handlers {
			descriptions = append(descriptions, &api.RouteDescription{Method: method, Path: route.Pattern})
		}
	}
	return descriptions
}

func (h *serviceHandler) RegisterRoutes(router chi.Router) {
	router.Mount("/", h.router)
}

func (h *serviceHandler) Generate(w http.ResponseWriter, r *http.Request) {
	var req api.GenerateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		message := err.Error()
		if errors.Is(err, io.EOF) {
			message = "request body is empty or incomplete"
		}
		slog.Error("Failed to decode request", "error", err)
		http.Error(w, message, http.StatusBadRequest)
		return
	}

	op := h.registry.FindOperation(req.Path, req.Method)
	res := h.gen.Request(&req, op, req.Context)
	api.NewJSONResponse(w).Send(res)
}

// returnedError is an error the service returned, with the status of the response it returned too.
// It has no Unwrap, so the adapter cannot answer an error type of the spec before returnedErrors.
type returnedError struct {
	status int
	err    error
}

func (e *returnedError) Error() string {
	return e.err.Error()
}

// returnedErrors hands next an error the service returned as it was returned, with the status of
// its response, so a service answers an error with the status it sets.
type returnedErrors struct {
	next ErrorHandler
}

func (h returnedErrors) HandleError(w http.ResponseWriter, r *http.Request, status int, err error) {
	var returned *returnedError
	if errors.As(err, &returned) {
		if returned.status != 0 {
			status = returned.status
		}
		err = returned.err
	}
	h.next.HandleError(w, r, status, err)
}

// generatorService calls the service first and makes a mock response when it returns nil, nil.
type generatorService struct {
	service   *service
	generator generator.Generate
	registry  typedef.OperationRegistry
}

var _ ServiceInterface = (*generatorService)(nil)

func (s *generatorService) ListUsers(ctx context.Context, opts *ListUsersServiceRequestOptions) (*ListUsersResponseData, error) {
	opts.GenerateResponse = func() (*ListUsersResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/users", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body ListUsersResponse200
		if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
			return nil, err
		}
		return NewListUsersResponseData(body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.ListUsers(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetUser(ctx context.Context, opts *GetUserServiceRequestOptions) (*GetUserResponseData, error) {
	opts.GenerateResponse = func() (*GetUserResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/users/{id}", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body User
		if err := api.UnmarshalResponseInto(res.Body, "application/json; charset=utf-8", &body); err != nil {
			return nil, err
		}
		return NewGetUserResponseData(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetUser(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetUserAvatar(ctx context.Context, opts *GetUserAvatarServiceRequestOptions) (*GetUserAvatarResponseData, error) {
	opts.GenerateResponse = func() (*GetUserAvatarResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/users/{id}/avatar", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body GetUserAvatarResponse200
		if err := api.UnmarshalResponseInto(res.Body, "image/png", &body); err != nil {
			return nil, err
		}
		return NewGetUserAvatarResponseData(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetUserAvatar(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetUserProfile(ctx context.Context, opts *GetUserProfileServiceRequestOptions) (*GetUserProfileResponseData, error) {
	opts.GenerateResponse = func() (*GetUserProfileResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/users/{id}/profile", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body GetUserProfileResponse200
		if err := api.UnmarshalResponseInto(res.Body, "text/html; charset=utf-8", &body); err != nil {
			return nil, err
		}
		return NewGetUserProfileResponseData(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetUserProfile(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) ExportUsers(ctx context.Context, opts *ExportUsersServiceRequestOptions) (*ExportUsersResponseData, error) {
	opts.GenerateResponse = func() (*ExportUsersResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/users/export", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body ExportUsersResponse200
		if err := api.UnmarshalResponseInto(res.Body, "text/csv", &body); err != nil {
			return nil, err
		}
		return NewExportUsersResponseData(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.ExportUsers(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetUserConfig(ctx context.Context, opts *GetUserConfigServiceRequestOptions) (*GetUserConfigResponseData, error) {
	opts.GenerateResponse = func() (*GetUserConfigResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/users/{id}/config", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body UserConfig
		if err := api.UnmarshalResponseInto(res.Body, "application/xml", &body); err != nil {
			return nil, err
		}
		return NewGetUserConfigResponseData(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetUserConfig(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetUserAPIData(ctx context.Context, opts *GetUserAPIDataServiceRequestOptions) (*GetUserAPIDataResponseData, error) {
	opts.GenerateResponse = func() (*GetUserAPIDataResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/users/{id}/api-data", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body User
		if err := api.UnmarshalResponseInto(res.Body, "application/vnd.api+json", &body); err != nil {
			return nil, err
		}
		return NewGetUserAPIDataResponseData(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetUserAPIData(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetUserHal(ctx context.Context, opts *GetUserHalServiceRequestOptions) (*GetUserHalResponseData, error) {
	opts.GenerateResponse = func() (*GetUserHalResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/users/{id}/hal", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body User
		if err := api.UnmarshalResponseInto(res.Body, "application/hal+json", &body); err != nil {
			return nil, err
		}
		return NewGetUserHalResponseData(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetUserHal(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetUserProblem(ctx context.Context, opts *GetUserProblemServiceRequestOptions) (*GetUserProblemResponseData, error) {
	opts.GenerateResponse = func() (*GetUserProblemResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/users/{id}/problem", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body User
		if err := api.UnmarshalResponseInto(res.Body, "application/problem+json", &body); err != nil {
			return nil, err
		}
		return NewGetUserProblemResponseData(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetUserProblem(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) StreamUsers(ctx context.Context, opts *StreamUsersServiceRequestOptions) (*StreamUsersResponseData, error) {
	opts.GenerateResponse = func() (*StreamUsersResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/users/stream", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		return NewStreamUsersResponseData(func(func([]byte) bool) {}).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.StreamUsers(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

func (s *generatorService) GetUserPdf(ctx context.Context, opts *GetUserPdfServiceRequestOptions) (*GetUserPdfResponseData, error) {
	opts.GenerateResponse = func() (*GetUserPdfResponseData, error) {
		respSchema := s.registry.GetResponseSchema("/users/{id}/pdf", "GET")
		res := s.generator.Response(respSchema, api.UserContextFromGoContext(ctx), generator.WithRequest(opts.RawRequest))
		var body GetUserPdfResponse200
		if err := api.UnmarshalResponseInto(res.Body, "application/pdf", &body); err != nil {
			return nil, err
		}
		return NewGetUserPdfResponseData(&body).WithHeaders(res.Headers), nil
	}

	resp, err := s.service.GetUserPdf(ctx, opts)
	if err != nil {
		status := 0
		if resp != nil {
			status = resp.Status
		}
		return nil, &returnedError{status: status, err: err}
	}
	if resp != nil {
		return resp, nil
	}
	return opts.GenerateResponse()
}

var (
	defaultFactory     *factory.Factory
	defaultFactoryOnce sync.Once
	defaultFactoryErr  error
)

// NewFactory returns a Factory with the spec, spec options and context of this service.
func NewFactory(opts ...factory.FactoryOption) (*factory.Factory, error) {
	openapiSpec, err := api.ReadEmbeddedSpec(openapiSpecFS)
	if err != nil {
		return nil, err
	}

	allOpts := []factory.FactoryOption{factory.WithServiceContext(contextSrc)}
	if cfg != nil && cfg.SpecOptions != nil {
		allOpts = append(allOpts, factory.WithSpecOptions(cfg.SpecOptions))
	}
	allOpts = append(allOpts, opts...)
	return factory.NewFactory(openapiSpec, allOpts...)
}

// GetFactory returns the Factory of this service, made on the first call.
func GetFactory() (*factory.Factory, error) {
	defaultFactoryOnce.Do(func() {
		defaultFactory, defaultFactoryErr = NewFactory()
	})
	return defaultFactory, defaultFactoryErr
}

// GenerateListUsersResponse makes a mock response for GET /users.
func GenerateListUsersResponse(ctx map[string]any) (*ListUsersResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/users", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body ListUsersResponse200
	if err := api.UnmarshalResponseInto(res.Body, "application/json", &body); err != nil {
		return nil, err
	}
	return NewListUsersResponseData(body).WithHeaders(res.Headers), nil
}

// GenerateListUsersRequest makes a mock request for GET /users.
func GenerateListUsersRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/users", "GET", ctx)
}

// GenerateGetUserResponse makes a mock response for GET /users/{id}.
func GenerateGetUserResponse(ctx map[string]any) (*GetUserResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/users/{id}", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body User
	if err := api.UnmarshalResponseInto(res.Body, "application/json; charset=utf-8", &body); err != nil {
		return nil, err
	}
	return NewGetUserResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateGetUserRequest makes a mock request for GET /users/{id}.
func GenerateGetUserRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/users/{id}", "GET", ctx)
}

// GenerateGetUserAvatarResponse makes a mock response for GET /users/{id}/avatar.
func GenerateGetUserAvatarResponse(ctx map[string]any) (*GetUserAvatarResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/users/{id}/avatar", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body GetUserAvatarResponse200
	if err := api.UnmarshalResponseInto(res.Body, "image/png", &body); err != nil {
		return nil, err
	}
	return NewGetUserAvatarResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateGetUserAvatarRequest makes a mock request for GET /users/{id}/avatar.
func GenerateGetUserAvatarRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/users/{id}/avatar", "GET", ctx)
}

// GenerateGetUserProfileResponse makes a mock response for GET /users/{id}/profile.
func GenerateGetUserProfileResponse(ctx map[string]any) (*GetUserProfileResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/users/{id}/profile", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body GetUserProfileResponse200
	if err := api.UnmarshalResponseInto(res.Body, "text/html; charset=utf-8", &body); err != nil {
		return nil, err
	}
	return NewGetUserProfileResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateGetUserProfileRequest makes a mock request for GET /users/{id}/profile.
func GenerateGetUserProfileRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/users/{id}/profile", "GET", ctx)
}

// GenerateExportUsersResponse makes a mock response for GET /users/export.
func GenerateExportUsersResponse(ctx map[string]any) (*ExportUsersResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/users/export", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body ExportUsersResponse200
	if err := api.UnmarshalResponseInto(res.Body, "text/csv", &body); err != nil {
		return nil, err
	}
	return NewExportUsersResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateExportUsersRequest makes a mock request for GET /users/export.
func GenerateExportUsersRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/users/export", "GET", ctx)
}

// GenerateGetUserConfigResponse makes a mock response for GET /users/{id}/config.
func GenerateGetUserConfigResponse(ctx map[string]any) (*GetUserConfigResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/users/{id}/config", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body UserConfig
	if err := api.UnmarshalResponseInto(res.Body, "application/xml", &body); err != nil {
		return nil, err
	}
	return NewGetUserConfigResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateGetUserConfigRequest makes a mock request for GET /users/{id}/config.
func GenerateGetUserConfigRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/users/{id}/config", "GET", ctx)
}

// GenerateGetUserAPIDataResponse makes a mock response for GET /users/{id}/api-data.
func GenerateGetUserAPIDataResponse(ctx map[string]any) (*GetUserAPIDataResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/users/{id}/api-data", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body User
	if err := api.UnmarshalResponseInto(res.Body, "application/vnd.api+json", &body); err != nil {
		return nil, err
	}
	return NewGetUserAPIDataResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateGetUserAPIDataRequest makes a mock request for GET /users/{id}/api-data.
func GenerateGetUserAPIDataRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/users/{id}/api-data", "GET", ctx)
}

// GenerateGetUserHalResponse makes a mock response for GET /users/{id}/hal.
func GenerateGetUserHalResponse(ctx map[string]any) (*GetUserHalResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/users/{id}/hal", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body User
	if err := api.UnmarshalResponseInto(res.Body, "application/hal+json", &body); err != nil {
		return nil, err
	}
	return NewGetUserHalResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateGetUserHalRequest makes a mock request for GET /users/{id}/hal.
func GenerateGetUserHalRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/users/{id}/hal", "GET", ctx)
}

// GenerateGetUserProblemResponse makes a mock response for GET /users/{id}/problem.
func GenerateGetUserProblemResponse(ctx map[string]any) (*GetUserProblemResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/users/{id}/problem", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body User
	if err := api.UnmarshalResponseInto(res.Body, "application/problem+json", &body); err != nil {
		return nil, err
	}
	return NewGetUserProblemResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateGetUserProblemRequest makes a mock request for GET /users/{id}/problem.
func GenerateGetUserProblemRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/users/{id}/problem", "GET", ctx)
}

// GenerateStreamUsersResponse makes a mock response for GET /users/stream.
func GenerateStreamUsersResponse(ctx map[string]any) (*StreamUsersResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/users/stream", "GET", ctx)
	if err != nil {
		return nil, err
	}
	return NewStreamUsersResponseData(func(func([]byte) bool) {}).WithHeaders(res.Headers), nil
}

// GenerateStreamUsersRequest makes a mock request for GET /users/stream.
func GenerateStreamUsersRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/users/stream", "GET", ctx)
}

// GenerateGetUserPdfResponse makes a mock response for GET /users/{id}/pdf.
func GenerateGetUserPdfResponse(ctx map[string]any) (*GetUserPdfResponseData, error) {
	f, err := GetFactory()
	if err != nil {
		return nil, err
	}
	res, err := f.Response("/users/{id}/pdf", "GET", ctx)
	if err != nil {
		return nil, err
	}
	var body GetUserPdfResponse200
	if err := api.UnmarshalResponseInto(res.Body, "application/pdf", &body); err != nil {
		return nil, err
	}
	return NewGetUserPdfResponseData(&body).WithHeaders(res.Headers), nil
}

// GenerateGetUserPdfRequest makes a mock request for GET /users/{id}/pdf.
func GenerateGetUserPdfRequest(ctx map[string]any) (schema.GeneratedRequest, error) {
	f, err := GetFactory()
	if err != nil {
		return schema.GeneratedRequest{}, err
	}
	return f.Request("/users/{id}/pdf", "GET", ctx)
}
